### PR TITLE
Add application_name_mode to xsec dataset

### PR DESCRIPTION
**Pull request by harterrt**
https://bugzilla.mozilla.org/show_bug.cgi?id=1331630

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/164)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by harterrt** [comment]
@vitillo, r?

**Comment by vitillo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/164#-:-Kas6kAGZwHjm-xc6qGx:bnfp4nl)*

**Comment by vitillo** [comment]
Please rebase.

**Pull request merged**
