### PR TITLE
Filter bad subsession lengths

### PR DESCRIPTION
**Pull request by harterrt**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/135)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by harterrt** [comment]
@vitillo, PTAL

**Comment by vitillo** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 79 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135#-KVQppC3t0b8QgWx32V4:-KVQppC4qMAe0bVLU1SF:b-y3q37) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7b0ce6646f1145e2420cbce1e325c06f1eab6f92/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L79)):*
> ```Scala
> 
>   private def bothOrNone[A, B](first: Option[A], second: Option[B]): Option[(A, B)] = {
>     first.flatMap(x => second.flatMap(y => Some((x, y))))
> ```

You should look into using for-comprehensions to deal with monads like `Option` as it makes the code more readable.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 97 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135#-KVQq4U7QPTR9cKDr4KD:-KVQq4U89Fr9WzQ4P1ZU:bxj6bsw) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7b0ce6646f1145e2420cbce1e325c06f1eab6f92/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L97)):*
> ```Scala
> 
>   def weightedMode[A](values: Option[Seq[A]]): Option[A] = {
>     bothOrNone(values, this.cleanSessionLength).flatMap(collate)
> ```

Same comment as above; this isn't very readable. It would also be convenient if you could format the code such that each operation has it's own line, e.g.:

```
foo().
bar(x, y).
car()
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135)*

**Comment by harterrt** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 79 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135#-KVQppC3t0b8QgWx32V4:-KVRys3eS7Kb4TFUUtMz:b-azqf7l) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7b0ce6646f1145e2420cbce1e325c06f1eab6f92/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L79)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> You should look into using for-comprehensions to deal with monads like `Option` as it makes the code more readable.
</details>
Great pointer, thanks!

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 97 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135#-KVQq4U7QPTR9cKDr4KD:-KVRzXNh2qUoLBK1dcGT:b-70aa3d) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7b0ce6646f1145e2420cbce1e325c06f1eab6f92/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L97)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Same comment as above; this isn't very readable. It would also be convenient if you could format the code such that each operation has it's own line, e.g.:
> 
> ```
> foo().
> bar(x, y).
> car()
> ```
</details>
RFAL, hopefully more readable now.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 79 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135#-KVRzHCfH3FSD7LiL4O0:-KVRzHCgbnhU_bGQ4fGA:bqjjqi) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/d2975bcaee13b03286605315b3925c73b7a4c839/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L79)):*
> ```Scala
> 
>   private def bothOrNone[A, B](pair: (Option[A], Option[B])): Option[(A, B)] = {
>     for {first <- pair._1; second <- pair._2} yield (first, second)
> ```

I'm happy with this version of the code, but I think a pattern matching solution may still be more readable. From what I read, pattern matching is generally considered code-smell. @vitillo & anyone following along, what's your opinion in this specific instance?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135)*

**Comment by harterrt** [comment]
@vitillo, PTAL

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 79 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135#-KVRzHCfH3FSD7LiL4O0:-KV_UPEffsSJIDAjYhUF:b-5l509g) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/d2975bcaee13b03286605315b3925c73b7a4c839/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L79)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary>
> I'm happy with this version of the code, but I think a pattern matching solution may still be more readable. From what I read, pattern matching is generally considered code-smell. @vitillo & anyone following along, what's your opinion in this specific instance?
</details>
I like this version :)

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 90 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135#-KV_V3bTK09yR9S_G1la:-KV_V3bUogfwietr3Oao:b4udhyw) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/d2975bcaee13b03286605315b3925c73b7a4c839/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L90)):*
> ```Scala
>     (for{v <- values; csl <- this.cleanSessionLength} yield (v, csl))
>       .flatMap(collate)
>       .map(_.flatMap(pair => bothOrNone(pair))) //remove value, weight pairs containing None
> ```

This is still not very readable. What about using `flatten` here or `filter(_.isDefined)` if you want to keep the `Option` type?

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 101 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135#-KV_WzJ2JvXnYbi2grw9:-KV_WzJ2JvXnYbi2grwA:b2nreh6) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/d2975bcaee13b03286605315b3925c73b7a4c839/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L101)):*
> ```Scala
>     (for{v <- values; csl <- this.cleanSessionLength} yield (v, csl))
>       .flatMap(collate)
>       .map(_.flatMap(pair => validatePair(pair)))
> ```

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135)*

**Comment by harterrt** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 90 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135#-KV_V3bTK09yR9S_G1la:-KV_eIdAe4n30M_eaLj1:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/d2975bcaee13b03286605315b3925c73b7a4c839/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L90)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> This is still not very readable. What about using `flatten` here or `filter(_.isDefined)` if you want to keep the `Option` type?
</details>
Done.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 101 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135#-KV_WzJ2JvXnYbi2grw9:-KV_eJI61wAYsrQGfxt7:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/d2975bcaee13b03286605315b3925c73b7a4c839/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L101)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Same as above.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135)*

**Comment by harterrt** [comment]
@vitillo, RFAL. Thanks!

---

Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135#-:-KV_hy5sj8eEKPWKzYO9:b3wazhj)*

**Comment by harterrt** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 90 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135#-KV_V3bTK09yR9S_G1la:-KVaVAMjxBA76gBG8us2:b-hs0898) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/d2975bcaee13b03286605315b3925c73b7a4c839/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L90)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary>
> Done.
</details>
Opening this back up per our offline conversation, @vitillo. It sounds like you're hoping to remove the nested calls to map/flatMap. At this stage, we're operating on an the pairs in a Option[Seq[Pair]]. I don't see a better way to handle the nested structure of this data. 

When you get a chance, let's spend 10m to video chat about this problem to make sure I understand correctly. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135)*

**Comment by vitillo** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 90 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135#-KV_V3bTK09yR9S_G1la:-KVb6IEXFBGoIYPV9MaV:bfdmocw) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/d2975bcaee13b03286605315b3925c73b7a4c839/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L90)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary>
> Opening this back up per our offline conversation, @vitillo. It sounds like you're hoping to remove the nested calls to map/flatMap. At this stage, we're operating on an the pairs in a Option[Seq[Pair]]. I don't see a better way to handle the nested structure of this data. 
> 
> When you get a chance, let's spend 10m to video chat about this problem to make sure I understand correctly. 
</details>
How about something like:

```
 def weightedMean(values: Option[Seq[Option[Long]]]): Option[Double] = {
    val cleaned = for {
      values <- values.toSeq
      sessionLengths <- this.cleanSessionLength.toSeq
      zipped <- collate(values, sessionLengths).toSeq
      tuple <- zipped
      first <- tuple._1
      second <- tuple._2
    } yield (first, second)

    aggregation.weightedMean(cleaned)
  }
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135)*

**Comment by harterrt** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 79 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135#-KVRzHCfH3FSD7LiL4O0:-KVeb07L8KGjGqIyf80F:biqer22) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/d2975bcaee13b03286605315b3925c73b7a4c839/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L79)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> I like this version :)
</details>
Removed since this is no longer used.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 90 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135#-KV_V3bTK09yR9S_G1la:-KVeaZyMP1cOSmV36-XP:b5d1y99) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/d2975bcaee13b03286605315b3925c73b7a4c839/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L90)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> How about something like:
> 
> ```
>  def weightedMean(values: Option[Seq[Option[Long]]]): Option[Double] = {
>     val cleaned = for {
>       values <- values.toSeq
>       sessionLengths <- this.cleanSessionLength.toSeq
>       zipped <- collate(values, sessionLengths).toSeq
>       tuple <- zipped
>       first <- tuple._1
>       second <- tuple._2
>     } yield (first, second)
> 
>     aggregation.weightedMean(cleaned)
>   }
> ```
</details>
Took me a while to grok what was going on here, but I learned something. RFAL, @vitillo.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 101 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135#-KV_WzJ2JvXnYbi2grw9:-KVebB91Nbj5Jdi0M15G:braud0i) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/d2975bcaee13b03286605315b3925c73b7a4c839/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L101)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary>
> Done.
</details>
Even more done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135)*

**Comment by harterrt** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 138 at r4](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135#-KVf0JlUcc_kb9zfReGp:-KVf0JlUcc_kb9zfReGq:b-j79srw) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/55048b5bbb0f8b35c0082078b07bf8ddbbee76ed/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L138)):*
> ```Scala
>   }
> 
>   def activeHoursByDOW(dow: Int): Option[Double] = {
> ```

@vitillo, take a look at this clean up. 

Here's an alternate version which doesn't require a branch: 
```scala
def activeHoursByDOW(dow: Int): Double = {    
  val hours = for {                                   
    csl <- this.cleanSessionLength.toSeq              
    psd <- this.parsedStartDate.toSeq                 
    pairs <- collate(csl, psd).toSeq                  
    pair <- pairs                                     
    if pair._2.getDayOfWeek == dow                    
    sessionLength <- pair._1                          
  } yield {sessionLength.toDouble / SECONDS_PER_HOUR} 
                                                      
  hours.sum                                     
}
```
I dislike this solution because it doesn't return an Optional value. We cannot then differentiate between 0 active hours caused by broken data and 0 active hours due to inactivity. Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135)*

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 138 at r4](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135#-KVf0JlUcc_kb9zfReGp:-KVf2RbF8LdtoVsQ0-oe:baks1bm) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/55048b5bbb0f8b35c0082078b07bf8ddbbee76ed/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L138)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary>
> @vitillo, take a look at this clean up. 
> 
> Here's an alternate version which doesn't require a branch: 
> ```scala
> def activeHoursByDOW(dow: Int): Double = {    
>   val hours = for {                                   
>     csl <- this.cleanSessionLength.toSeq              
>     psd <- this.parsedStartDate.toSeq                 
>     pairs <- collate(csl, psd).toSeq                  
>     pair <- pairs                                     
>     if pair._2.getDayOfWeek == dow                    
>     sessionLength <- pair._1                          
>   } yield {sessionLength.toDouble / SECONDS_PER_HOUR} 
>                                                       
>   hours.sum                                     
> }
> ```
> I dislike this solution because it doesn't return an Optional value. We cannot then differentiate between 0 active hours caused by broken data and 0 active hours due to inactivity. Thoughts?
> 
</details>
Agreed. The branched solution is fine as it is much easier to understand.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135)*

**Comment by harterrt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 138 at r4](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135#-KVf0JlUcc_kb9zfReGp:-KVfhd3AZCkhD3tHSF64:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/55048b5bbb0f8b35c0082078b07bf8ddbbee76ed/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L138)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Agreed. The branched solution is fine as it is much easier to understand.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/135)*

**Pull request merged**
