### PR TITLE
Add documentation for MainSummary dataset

### PR DESCRIPTION
**Pull request by mreid-moz**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/91)

### CODE REVIEW

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/MainSummary.md, line 20 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/91#-KLvOasEemMuLObVWESt:-KLvOasEemMuLObVWESu:-822219143) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ff97e95a47bc8cb5bec3253f50585d60ad558d6/docs/MainSummary.md#L20)):*
> ```Markdown
>     --master yarn-client \
>     --class com.mozilla.telemetry.views.MainSummaryView \
>     telemetry-batch-view-1.1.jar \
> ```

Fix indentation

---

*[docs/MainSummary.md, line 29 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/91#-KLvOhPNSFZcih0WLEVg:-KLvOhPNSFZcih0WLEVh:-418351641) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ff97e95a47bc8cb5bec3253f50585d60ad558d6/docs/MainSummary.md#L29)):*
> ```Markdown
> * This dataset is updated daily via the [telemetry-airflow](https://github.com/mozilla/telemetry-airflow) infrastructure.
> * The job DAG runs every day shortly after midnight UTC.
> * The job saves the resulting data to S3 as [Parquet](https://parquet.apache.org/)-serialized [DataFrames](https://spark.apache.org/docs/1.6.0/api/java/org/apache/spark/sql/DataFrame.html), under prefixes of the form `main_summary/v3/submission_date_s3=(YYYYMMDD SUBMISSION DATE)/sample_id=(INT VALUE)` in the `telemetry-parquet` bucket.
> ```

Please link to the latest version of the DataFrame API.

---

*[docs/MainSummary.md, line 142 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/91#-KLvOwyoZovuf85xB7Nm:-KLvOwyoZovuf85xB7Nn:-918473642) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ff97e95a47bc8cb5bec3253f50585d60ad558d6/docs/MainSummary.md#L142)):*
> ```Markdown
> Most of the fields are simple scalar values, with a few notable exceptions.
> 
> The `search_count` field is an array of structs, each item in the array representing
> ```

It would be nice to have the description of the fields in a bullet list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/91)*

**Comment by mreid-moz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/MainSummary.md, line 20 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/91#-KLvOasEemMuLObVWESt:-KLvehhaDrO9D12-GBKr:1886821058) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ff97e95a47bc8cb5bec3253f50585d60ad558d6/docs/MainSummary.md#L20)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Fix indentation
</details>
How should the indentation look?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/91)*

**Comment by mreid-moz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/MainSummary.md, line 29 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/91#-KLvOhPNSFZcih0WLEVg:-KLvhXCR_H7jsTPZ_5lP:-499146009) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ff97e95a47bc8cb5bec3253f50585d60ad558d6/docs/MainSummary.md#L29)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Please link to the latest version of the DataFrame API.
</details>
Done.

---

*[docs/MainSummary.md, line 142 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/91#-KLvOwyoZovuf85xB7Nm:-KLvhZZXI0PhU4XECfiq:-499146009) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ff97e95a47bc8cb5bec3253f50585d60ad558d6/docs/MainSummary.md#L142)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> It would be nice to have the description of the fields in a bullet list.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/91)*

**Comment by vitillo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/MainSummary.md, line 20 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/91#-KLvOasEemMuLObVWESt:-KLwBcTGrQruSFYYEl3P:458950564) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ff97e95a47bc8cb5bec3253f50585d60ad558d6/docs/MainSummary.md#L20)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>
> How should the indentation look?
</details>
Nevermind, it just looks a bit weird but it does make sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/91)*

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/91)*

**Comment by vitillo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/91#-:-KLwC0EKIJXbbtcd79Ol:1417088721)*

**Pull request merged**
