### PR TITLE
Add HBase ETL job for main summary dataset.

### PR DESCRIPTION
**Pull request by vitillo**
We want to evaluate HBase to access the history of individual clients as filtering out individual clients from the `main_summary` dataset is very slow. At the end of January we will decide if we want to keep investing into it or not depending on its usefulness.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/154)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by vitillo** [comment]
@mreid-moz r?

**Comment by mreid-moz** [comment]
This looks good, but is there any way to add even some basic test coverage?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[build.sbt, line 29 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-KZfsqE37yF6ra7eyOOh:-KZfsqE44G_Xxao4QBKE:bqd03qo) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0de8f2bae313e8138f20717e15c489d9daccd17f/build.sbt#L29)):*
> ```Scala
>     libraryDependencies += "org.apache.spark" %% "spark-mllib" % "2.0.0",
>     libraryDependencies += "org.apache.spark" %% "spark-hive" % "2.0.0",
>     libraryDependencies += "org.apache.hbase" % "hbase-server" % "1.2.3",
> ```

Can we use `1.2.4`?

---

*[src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala, line 74 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-KZfueWrEGSgUCYGO2Bo:-KZfueWsrYONL-7IFGIg:bwz3d1l) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0de8f2bae313e8138f20717e15c489d9daccd17f/src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala#L74)):*
> ```Scala
> 
>         val rdd = subset.rdd.zip(jsonData).flatMap{ case (row, json) =>
>           val clientId = row.getAs[String](0)
> ```

You can just use `row.getString(0)`

---

*[src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala, line 86 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-KZfrgN-mxGJw9RFymHH:-KZfrgN0Z803_WiUSmUj:b97w1hp) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0de8f2bae313e8138f20717e15c489d9daccd17f/src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala#L86)):*
> ```Scala
>             Some((s"$clientId:$formattedDate:$documentId", Seq((json, ts))))
>           } catch {
>             case _: Throwable =>
> ```

Please add an accumulator to count these errors and log the resulting count.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-:-KZg-UpStj-iMpkcXUxp:b-czm03d)*

**Comment by mreid-moz** [comment]
Also, how is the corresponding HBase cluster provisioned?

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-:-KZg-knAiyeyqkzlkCop:b-e51mp2)*

**Comment by vitillo** [comment]
I have improved the test coverage. You can find the provisioning script [here](https://github.com/vitillo/emr-bootstrap-hbase).

---

Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[build.sbt, line 29 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-KZfsqE37yF6ra7eyOOh:-K_9SXPpK5L7OM3XQ0eh:b-7clgsf) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0de8f2bae313e8138f20717e15c489d9daccd17f/build.sbt#L29)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

Can we use `1.2.4`?
</blockquote></details>

No, as it's not supported yet by EMR.

---

*[src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala, line 74 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-KZfueWrEGSgUCYGO2Bo:-K_9Segm0ApTgEQtXY8_:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0de8f2bae313e8138f20717e15c489d9daccd17f/src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala#L74)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

You can just use `row.getString(0)`
</blockquote></details>

Done.

---

*[src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala, line 86 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-KZfrgN-mxGJw9RFymHH:-K_9SgmehpnLI3hc2SML:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0de8f2bae313e8138f20717e15c489d9daccd17f/src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala#L86)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

Please add an accumulator to count these errors and log the resulting count.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-:-K_9Sjq2zz8Or1TOEKkx:b8hrpi2)*

**Comment by mreid-moz** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala, line 26 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-K_9lo1fzH1Yefm6orsp:-K_9lo1fzH1Yefm6orsq:b146iqb) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8a8a0a153df5ec586cb2cba37a16ead8ea270e34/src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala#L26)):*
> ```Scala
>   private[views] val column = "payload"
> 
>   private[views] def createHbaseTable(useCompression: Boolean = true)(implicit config: HBaseConfig): Unit = {
> ```

please rename to `createHBaseTable` for consistency with other HBase function naming.

---

*[src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala, line 86 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-K_9oTHzXdHPGGkrSVQ6:-K_9oTHzXdHPGGkrSVQ7:bqj0ymw) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8a8a0a153df5ec586cb2cba37a16ead8ea270e34/src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala#L86)):*
> ```Scala
> 
>         rdd.toHBaseBulk(tableName, columnFamily, List(column))
>         println(s"${errorAcc.value} validation errors encountered")
> ```

maybe this error count should be returned or otherwise exposed for test purposes.

---

*[src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala, line 89 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-K_9kXLhAnlHM8asWXIZ:-K_9kXLicm--gdpK1lgT:b-82sue3) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8a8a0a153df5ec586cb2cba37a16ead8ea270e34/src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala#L89)):*
> ```Scala
>       }
>     }
> ```

nit: please remove this empty line.

---

*[src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala, line 107 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-K_9k_MqK2BDIFKN5N7r:-K_9k_Mra77P8zjdFS_0:b-vndqg7) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8a8a0a153df5ec586cb2cba37a16ead8ea270e34/src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala#L107)):*
> ```Scala
> 
>     implicit val hbaseConfig = HBaseConfig("hbase.zookeeper.quorum" -> conf.hbaseMaster())
>     implicit val spark = SparkSession.builder().master("yarn").appName("HBaseExample").getOrCreate()
> ```

s/HBaseExample/HBaseMainSummaryView/

---

*[src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala, line 19 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-K_9lZj2j4djNGy2vlsW:-K_9lZj2j4djNGy2vlsX:b-vndqg7) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8a8a0a153df5ec586cb2cba37a16ead8ea270e34/src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala#L19)):*
> ```Scala
>   val admin = new HBaseAdmin(hbaseConfig.get)
> 
>   implicit val spark = SparkSession.builder().master("local[*]").appName("HBaseExample").getOrCreate()
> ```

s/HBaseExample/HBaseMainSummaryView/

---

*[src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala, line 28 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-K_9mAUhNK5etjT1UhkM:-K_9mAUhNK5etjT1UhkN:b-3bjvrm) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8a8a0a153df5ec586cb2cba37a16ead8ea270e34/src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala#L28)):*
> ```Scala
>     }
> 
>     HBaseMainSummaryView.createHbaseTable(useCompression = false)
> ```

Please add an assert that the table does not exist before creating.

---

*[src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala, line 33 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-K_9mGikDbLxgZZ8GB-i:-K_9mGikDbLxgZZ8GB-j:bvmjwuj) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8a8a0a153df5ec586cb2cba37a16ead8ea270e34/src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala#L33)):*
> ```Scala
> 
>   it should "not fail if the HBase table already exists" in {
>     HBaseMainSummaryView.createHbaseTable(useCompression = false)
> ```

+ assert that the table already exists above this.

---

*[src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala, line 52 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-K_9mhMO_Wf9jCuTxo44:-K_9mhMO_Wf9jCuTxo45:b-rces3n) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8a8a0a153df5ec586cb2cba37a16ead8ea270e34/src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala#L52)):*
> ```Scala
>     assert(table.size == 1)
>     assert(table(0)._1 == "foo:20161228:bar")
>     assert(table(0)._2("cf")("payload") == """{"subsession_start_date":"2016-12-28T00:00:00.0+00:00","channel":"release"}""")
> ```

It would be better to parse the resulting JSON and check fields directly in case the serialization varies in different configurations.

---

*[src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala, line 66 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-K_9n9mdDg4vJLMuiPjW:-K_9n9menfELIJSj8VAg:b-ck1aez) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8a8a0a153df5ec586cb2cba37a16ead8ea270e34/src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala#L66)):*
> ```Scala
>     assert(table.size == 1)
>     assert(table(0)._1 == "foo:20161228:bar")
>     assert(table(0)._2("cf")("payload") == """{"subsession_start_date":"2016-12-28T00:00:00.0+00:00","channel":"nightly"}""")
> ```

Same suggestion here re: parsing the JSON.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154)*

**Comment by vitillo** [comment]
Review status: 3 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala, line 28 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-K_9mAUhNK5etjT1UhkM:-K_9qgEylLv62-daMg6L:bmr7cqw) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8a8a0a153df5ec586cb2cba37a16ead8ea270e34/src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala#L28)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

Please add an assert that the table does not exist before creating.
</blockquote></details>

Not sure I understand what you mean; how can it exists if it gets deleted right before?

---

*[src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala, line 33 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-K_9mGikDbLxgZZ8GB-i:-K_9qqYo8m6XrgRxWZZv:b-xgutyd) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8a8a0a153df5ec586cb2cba37a16ead8ea270e34/src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala#L33)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

+ assert that the table already exists above this.
</blockquote></details>

The table must exists if the earlier test didn't fail.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154)*

**Comment by mreid-moz** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala, line 28 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-K_9mAUhNK5etjT1UhkM:-K_9tqlAhXEPJjTygIeq:b-y31zkh) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8a8a0a153df5ec586cb2cba37a16ead8ea270e34/src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala#L28)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary><blockquote>

Not sure I understand what you mean; how can it exists if it gets deleted right before?
</blockquote></details>

Just to make sure that the expected pre-condition holds immediately before the code runs. Maybe the table deletion is a deferred action, or happens at next compaction etc.

---

*[src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala, line 33 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-K_9mGikDbLxgZZ8GB-i:-K_9v5MYOB51DHYBxqhd:b-c5kqpr) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8a8a0a153df5ec586cb2cba37a16ead8ea270e34/src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala#L33)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary><blockquote>

The table must exists if the earlier test didn't fail.
</blockquote></details>

Hm, I thought you could run a specific test task via `sbt testOnly ...`, but it looks like you can just run an entire class. Never mind.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154)*

**Comment by vitillo** [comment]
Review status: 1 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala, line 26 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-K_9lo1fzH1Yefm6orsp:-K_A3cmyQ0etYCDXN691:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8a8a0a153df5ec586cb2cba37a16ead8ea270e34/src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala#L26)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

please rename to `createHBaseTable` for consistency with other HBase function naming.
</blockquote></details>

Done.

---

*[src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala, line 89 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-K_9kXLhAnlHM8asWXIZ:-K_A3b3eMCYvMse7lyM8:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8a8a0a153df5ec586cb2cba37a16ead8ea270e34/src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala#L89)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

nit: please remove this empty line.
</blockquote></details>

Done.

---

*[src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala, line 107 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-K_9k_MqK2BDIFKN5N7r:-K_A3cAbBgn3MhVDkrWC:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8a8a0a153df5ec586cb2cba37a16ead8ea270e34/src/main/scala/com/mozilla/telemetry/views/HBaseMainSummaryView.scala#L107)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

s/HBaseExample/HBaseMainSummaryView/
</blockquote></details>

Done.

---

*[src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala, line 28 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-K_9mAUhNK5etjT1UhkM:-K_A3iJouQonJBvEnURJ:b-p8p4sc) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8a8a0a153df5ec586cb2cba37a16ead8ea270e34/src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala#L28)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

Just to make sure that the expected pre-condition holds immediately before the code runs. Maybe the table deletion is a deferred action, or happens at next compaction etc.
</blockquote></details>

The operation should be synchronous afaik.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154)*

**Comment by mreid-moz** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala, line 52 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-K_9mhMO_Wf9jCuTxo44:-K_A6dn1S-F3lx9oaanv:bibqnov) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8a8a0a153df5ec586cb2cba37a16ead8ea270e34/src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala#L52)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

It would be better to parse the resulting JSON and check fields directly in case the serialization varies in different configurations.
</blockquote></details>

Let's handle this in a follow-up if tests start failing.

---

*[src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala, line 66 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-K_9n9mdDg4vJLMuiPjW:-K_A6hhm4m2EZannJrvD:b-7ropln) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8a8a0a153df5ec586cb2cba37a16ead8ea270e34/src/test/scala/com/mozilla/telemetry/views/HBaseMainSummaryViewTest.scala#L66)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

Same suggestion here re: parsing the JSON.
</blockquote></details>

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/154#-:-K_A6bGhWkOQTZ1up1lb:bnfp4nl)*

**Pull request merged**
