### PR TITLE
Add some more notes about using the IDE on Windows

### PR DESCRIPTION
**Pull request by mhammond**
I made some notes when installing and trying to use IntelliJ which I've captured here.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/137)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by Dexterp37** [comment]
Drive-by: @mhammond, maybe you should integrate this at the end of the README? I've added a Windows issues a while back that reports some of the things you've added.

**Comment by mhammond** [comment]
> maybe you should integrate this at the end of the README?

I prefer having the windows notes on the IDE close to the other notes about the IDE - the other Windows notes also seem relevant to the immediate section above it. I'm happy to move it if that's really wanted though (or have it re-jigged in-place as part of merging it :)

**Comment by Dexterp37** [comment]
Yeah, I mean, I don't particularly care I'm just saying that the two sections should probably be merged (as they suggest the same solutions!)

**Pull request closed without merging**
