### PR TITLE
Bug 1325974 - retrieve processType from the right field

### PR DESCRIPTION
**Pull request by maurodoglio**
This is to fix the change introduced in https://github.com/mozilla/telemetry-batch-view/pull/130

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/156)

### CODE REVIEW

**Comment by maurodoglio** [comment]
I verified this is working using [this notebook](https://gist.github.com/maurodoglio/c6d8e49f5b31dbdd035cf2a21dbb6153). The result is in line with [the numbers before Dec 17](https://sql.telemetry.mozilla.org/queries/2005#3599)

**Comment by maurodoglio** [comment]
@harterrt do you have some spare cycles for a review?

**Comment by harterrt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala, line 63 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/156#-K_BcsevrtX0S2OWuYPa:-K_BcooVnlhmi0TKzpFf:b-9ir8vd) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/1ca8cb11e76013a4c08f4958775f24fd16fcd947/src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala#L63)):*
> ```Scala
>               val payload = message.payload match {
>                 case Some(value: String) => parse(value)
>                 case _ => JNothing
> ```

What are these nested case statements doing? Is it dealing with nested `Option` types? If so, can we use a for comprehension instead?

---

*[src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala, line 157 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/156#-K_BdZ-CURUwnFLB2MQf:-K_BdZ-CURUwnFLB2MQg:b-n4w04m) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/1ca8cb11e76013a4c08f4958775f24fd16fcd947/src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala#L157)):*
> ```Scala
>         case Some("crash") => m.get("payload") match {
>           case Some(payload: JValue) => payload \ "payload" \ "processType" match {
>             case JString("browser") | JNothing => true
> ```

Same question as above.

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 138 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/156#-K_BcFEL6AfTY3FwcxeH:-K_BcFEMCWaKf43yRM4e:b-vakfw) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/1ca8cb11e76013a4c08f4958775f24fd16fcd947/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L138)):*
> ```Scala
>         "payload.keyedHistograms" -> compact(render(keyedHistograms)),
>         "payload.info" -> compact(render(info)),
>         "payload" -> parse(payload),
> ```

Why parse the payload here?

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 270 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/156#-K_Bezw3HWUe8_0h9quE:-K_Bezw4gYYuZefeg2po:b-n0k3ns) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/1ca8cb11e76013a4c08f4958775f24fd16fcd947/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L270)):*
> ```Scala
>       ) = CrashAggregateView.compareCrashes(sc.get, sc.get.parallelize(contentCrashPings))
>     rowRDD.collect()
>     assert(crashProcessedAccumulator.value == 0)
> ```

Why was this test passing before? Was the altered ping malformed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/156)*

**Comment by maurodoglio** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala, line 63 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/156#-K_BcsevrtX0S2OWuYPa:-K_FAIlatnz81cixmPjp:bxkflgb) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/1ca8cb11e76013a4c08f4958775f24fd16fcd947/src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala#L63)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary><blockquote>

What are these nested case statements doing? Is it dealing with nested `Option` types? If so, can we use a for comprehension instead?
</blockquote></details>

The logic here is to parse the payload of a ping only if it's a crash ping. I'm not sure how to express that as a for comprehension though.

---

*[src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala, line 157 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/156#-K_BdZ-CURUwnFLB2MQf:-K_Fdack_NAPvMC1W2ae:b78rpsf) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/1ca8cb11e76013a4c08f4958775f24fd16fcd947/src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala#L157)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary><blockquote>

Same question as above.
</blockquote></details>

Again, I'm not sure how to express this with a for comprehension

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 138 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/156#-K_BcFEL6AfTY3FwcxeH:-K_FcNSGjrZp8jukD1Jy:b-uhuq2r) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/1ca8cb11e76013a4c08f4958775f24fd16fcd947/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L138)):*
> parse(payload),
In CrashAggregatesView the payload is parsed before the fields map is passed to compareCrashes so I'm doing the same here

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 270 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/156#-K_Bezw3HWUe8_0h9quE:-K_FdCYFF4RdGcYcLzB_:bifxgk4) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/1ca8cb11e76013a4c08f4958775f24fd16fcd947/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L270)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary><blockquote>

Why was this test passing before? Was the altered ping malformed?
</blockquote></details>

Yes. The altered ping had the processType property in the wrong place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/156)*

**Comment by harterrt** [comment]
Thanks, :LGTM:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala, line 63 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/156#-K_BcsevrtX0S2OWuYPa:-K_FnkZawJ5g36b9D7QQ:b32w0x) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/1ca8cb11e76013a4c08f4958775f24fd16fcd947/src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala#L63)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary><blockquote>

The logic here is to parse the payload of a ping only if it's a crash ping. I'm not sure how to express that as a for comprehension though.
</blockquote></details>

OK

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 138 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/156#-K_BcFEL6AfTY3FwcxeH:-K_Fn_5P2Tk0_jx1cDC7:bb6ywmx) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/1ca8cb11e76013a4c08f4958775f24fd16fcd947/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L138)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary><blockquote>

> parse(payload),
In CrashAggregatesView the payload is parsed before the fields map is passed to compareCrashes so I'm doing the same here
</blockquote></details>

LGTM

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 270 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/156#-K_Bezw3HWUe8_0h9quE:-K_Fn28-oneHP7BbrtuA:bia3c5v) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/1ca8cb11e76013a4c08f4958775f24fd16fcd947/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L270)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary><blockquote>

Yes. The altered ping had the processType property in the wrong place.
</blockquote></details>

Sounds like the issue was that the tests were internally consistent but expected the Heka message to include  a parsed field that wasn't there. For context, I had a similar issue in Bug 1325653.

This code is correct as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/156#-:-K_Fo8J8KN3aSHZZxlgO:bgl8jla)*

**Pull request merged**
