### PR TITLE
Bug 1305742 - Add gfx_compositor to CrashAggregatesView dimensions

### PR DESCRIPTION
**Pull request by maurodoglio**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/123)

### CODE REVIEW

**Comment by vitillo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala, line 260 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123#-KTUSdR-nSvCcp7BSq4N:-KTUSdR-nSvCcp7BSq4O:bbtige4) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/20ea5b624e77d517033ab85137dde8aaae42d936/src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala#L260)):*
> ```Scala
>               Some(topLevelField)
>             } else { // JSON field, the rest of the path tells us where to look in the JSON
>               val is_gfx_compositor = dimensionNames(index).equals("gfx_compositor")
> ```

What guarantee do we have that `dimensionNames(i) == compareableDimensions(i)`?

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 237 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123#-KTUU0khCdm4BqizLFpp:-KTUU0kioqnXEKUH2ZI7:b-mjla7o) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/20ea5b624e77d517033ab85137dde8aaae42d936/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L237)):*
> ```Scala
>     ("e10s", List(true)),
>     ("e10s_cohort", List("control")),
>     ("gfx_compositor", List("simple", "none", null))
> ```

That much code duplication doesn't look very clean; could you please add those values in the original test and use some simple math to derive the results? As long as it's commented it will be fine since we are planning to rewrite this job.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123)*

**Comment by maurodoglio** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala, line 260 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123#-KTUSdR-nSvCcp7BSq4N:-KThNFadueShkucgJGSF:b-ytznme) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/20ea5b624e77d517033ab85137dde8aaae42d936/src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala#L260)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> What guarantee do we have that `dimensionNames(i) == compareableDimensions(i)`?
</details>
The way this view was written requires those lists to be kept in sync. Ideally those lists should be keys and values of a Map, but I would leave that change for another PR.

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 237 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123#-KTUU0khCdm4BqizLFpp:-KThgjACv3i-9k_HvXH8:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/20ea5b624e77d517033ab85137dde8aaae42d936/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L237)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> That much code duplication doesn't look very clean; could you please add those values in the original test and use some simple math to derive the results? As long as it's commented it will be fine since we are planning to rewrite this job.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123)*

**Comment by maurodoglio** [comment]
argh

**Comment by maurodoglio** [comment]
To circumvent the memory issues I changed the Travis configuration to run on the `standard` infrastructure. I also filed [Bug 1309214](https://bugzilla.mozilla.org/show_bug.cgi?id=1309214) to determine and fix the root cause.

**Comment by vitillo** [comment]
Reviewed 2 of 2 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 203 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123#-KTnyvjMaJhaEAhP6Eti:-KTnyvjNMm_VmJ6a0LvD:b-2co4p1) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/554cd90969448d208b2324b7123767bd240f18c3/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L203)):*
> ```Scala
> 
>   "crash rates" must "be converted correctly" in {
>     // We needa special case for gfx_compositor, since it has 2 values that count as one.
> ```

s/needa/need

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 223 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123#-KTo-09r-zWX0nEMdUC8:-KTo-09r-zWX0nEMdUC9:bxqz97t) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/554cd90969448d208b2324b7123767bd240f18c3/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L223)):*
> ```Scala
>       val stats = row.getJavaMap[String, Double](0)
>       // We have 2 pings, one for gfx_compositor = 'none' and another one for gfx_compositor = null
>       assert(stats("ping_count")                       == 2)
> ```

Could we refactor the code so that we minimize duplication since the only thing that changes is the ping count?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123)*

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123)*

**Comment by maurodoglio** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 203 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123#-KTnyvjMaJhaEAhP6Eti:-KTokrGlxW1G_o8iNVsD:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/554cd90969448d208b2324b7123767bd240f18c3/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L203)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> s/needa/need
</details>
Done.

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 223 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123#-KTo-09r-zWX0nEMdUC8:-KTokvEuz2sK2RXnVJWy:b-yu4inq) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/554cd90969448d208b2324b7123767bd240f18c3/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L223)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Could we refactor the code so that we minimize duplication since the only thing that changes is the ping count?
</details>
I refactored the code, and I noticed that the all counts actually change. I don't know what I was doing wrong, but it now makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123)*

**Comment by maurodoglio** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 223 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123#-KTo-09r-zWX0nEMdUC8:-KTolgDrT1A3iaHlQoAb:b-29t0a2) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/554cd90969448d208b2324b7123767bd240f18c3/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L223)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary>
> I refactored the code, and I noticed that the all counts actually change. I don't know what I was doing wrong, but it now makes sense.
</details>
Also, there are no magic numbers anymore. Other than 42 of course :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123)*

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 223 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123#-KTo-09r-zWX0nEMdUC8:-KTow3Xp9hw_Gd3W2jAK:b7epjym) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/554cd90969448d208b2324b7123767bd240f18c3/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L223)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary>
> Also, there are no magic numbers anymore. Other than 42 of course :smile: 
</details>
This worries me, we should understand why these tests weren't failing. Are these asserts executed at all? Does `rdd.filter` ignore fields with `nulls` in it?

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 204 at r5](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123#-KToueLP8lWMcffSnfcK:-KToueLP8lWMcffSnfcL:beigm3g) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/a6a93f91c24f1f556375533da107dea131fb5d5a/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L204)):*
> ```Scala
>   "gfx_backend" must "be either a string or null" in {
>     val values = fixture.records.select("dimensions.gfx_compositor").distinct().rdd.map(r => r(0)).collect()
>     assert(values.toSet == Set("simple", null))
> ```

At the cost of being pedantic, there is no test for the third case which behaves somewhat differently than the others. That said, I am aware of the urgency and of the memory issues that arise with the cartesian product so we could address this in the follow up bug.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123)*

**Comment by maurodoglio** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 223 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123#-KTo-09r-zWX0nEMdUC8:-KTpVXsLFQ73DjeheYah:bz9ycu6) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/554cd90969448d208b2324b7123767bd240f18c3/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L223)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> This worries me, we should understand why these tests weren't failing. Are these asserts executed at all? Does `rdd.filter` ignore fields with `nulls` in it?
</details>
Yeah the reason is the filter on the null values. I tried to run this test
```scala
"null values " must "be automaticall filtered" in {
    assert(fixture.records.filter("dimensions.gfx_compositor != 'simple'").count() == 0)
    assert(fixture.records.filter("dimensions.gfx_compositor IS NULL").count() == 16384)
  }
```
and it passes. [Here](http://stackoverflow.com/questions/34117167/spark-sqls-where-clause-excludes-null-values) is a SO thread about it.

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 204 at r5](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123#-KToueLP8lWMcffSnfcK:-KTpf09Bb0lpvTyz93g9:bxlkmsu) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/a6a93f91c24f1f556375533da107dea131fb5d5a/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L204)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> At the cost of being pedantic, there is no test for the third case which behaves somewhat differently than the others. That said, I am aware of the urgency and of the memory issues that arise with the cartesian product so we could address this in the follow up bug.
</details>
You mean the case where a ping doesn't have the gfx compositor property at all? Yeah, Let's address it in [bug 1309214](https://bugzilla.mozilla.org/show_bug.cgi?id=1309214)  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/123)*

**Comment by vitillo** [comment]
r+

**Pull request merged**
