### PR TITLE
Make cross_sectional handle dates more robustly

### PR DESCRIPTION
**Pull request by harterrt**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/138)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by harterrt** [comment]
@vitillo, as discussed offline, this change will fix the issues causing crashes in the weekly xsec job.

**Comment by vitillo** [comment]
The commit should have a description mentioning what `robustly` means.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 194 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/138#-KVjQdsLB--0ZKlkTPBF:-KVjQdsLB--0ZKlkTPBG:b-jtnffk) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/494441a226f3a4248eb1ba416dcdc87901914d8f/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L194)):*
> ```Scala
>       pairs <- collate(ssd, sd)
>     } yield { 
>       pairs.map(pair => getDateDiff(pair._1, pair._2))
> ```

Can we move the map inside the for comprehension?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/138#-:-KVjQytrXYolZiGps0Pi:b-cdor3t)*

**Comment by harterrt** [comment]
Amended:

This implementation introduces error handling to the date parsing and
allows for dates with more or fewer than 10 characters.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 194 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/138#-KVjQdsLB--0ZKlkTPBF:-KVjTJ_m72s_-tGgd8bm:b-hbzc92) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/819ebeff84a3e7edfc17450d5be978c0b0bc3bff/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L194)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Can we move the map inside the for comprehension?
</details>
Moving this inside the for comprehension would force us to flatten the Option to a Seq, i.e. we'd have to return a Seq[Option[Long]]. 

This would make it impossible to differentiate between missing data and broken data (missing submission_date or subsession_start_date and sequences with different lengths)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/138#-:-KVjUgvUf4fvEE0csVKH:b-n6g5u)*

**Comment by harterrt** [comment]
@vitillo, RFAL

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/138#-:-KVjUy0s-fHnrNiN_4Ko:b-t3deqp)*

**Comment by vitillo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/138#-:-KVjaDWsCscRzkOnguSx:bnfp4nl)*

**Pull request merged**
