### PR TITLE
Add events to MainSummaryView

### PR DESCRIPTION
**Pull request by sunahsuh**
Since we're getting events in nightly and aurora now, we need to start presenting them for analysis.

I'm not 100% sure that Main Summary is the right place for this, but if we're processing main pings anyway adding a new column shouldn't be a huge deal, if I understand how Parquet works correctly. My next step after this would be to pull out an events dataset much like we do with addons.

Extracting the parameters is kind of ugly since events are a list of lists instead of a list of objects, so we can't use json4s's case class extractors. I attempted to write a custom deserializer for an Events case class but it ended up just looking like this anyway, just in a different file. Open to suggestions for how to get this looking more idiomatic -- working with variable-length heterogeneous lists in Scala has proved to be.. difficult.

I've successfully run this on recently nightly pings and read in events from the resultant files in a jupyter notebook.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/160)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by sunahsuh** [comment]
@mreid-moz r?

**Comment by mreid-moz** [comment]
Looks good, a few minor comments. I can't think of a more idiomatic way to handle these variable-length lists, your approach seems reasonable to me.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, line 189 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/160#-K_jG271EjaV08lLqArd:-K_jG272WFItMFdKY84c:b-gmzg36) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/e27d07b442a80d54834d019bc6b9a5fd57020d49/src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala#L189)):*
> ```Scala
>   }
> 
>   def getEvents(events: JValue): Option[List[Row]]  = {
> ```

nit: replace two spaces with one before the `=`

---

*[src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, line 195 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/160#-K_jG5PrEM1AmgZznCv3:-K_jG5PrEM1AmgZznCv4:b-jzm7yi) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/e27d07b442a80d54834d019bc6b9a5fd57020d49/src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala#L195)):*
> ```Scala
>         val rows = eventList.flatMap {
>           case _ @ List(
>             timestamp : BigInt,
> ```

nit: remove the spaces before the colons here and below

---

*[src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, line 563 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/160#-K_jITkB2A2YDQhKKppc:-K_jITkCOh3DYhOWRg0Q:b2ab0n8) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/e27d07b442a80d54834d019bc6b9a5fd57020d49/src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala#L563)):*
> ```Scala
> 
>   def buildEventSchema = StructType(List(
>     StructField("timestamp", LongType, nullable = false),
> ```

Other sub-schemas are vertically aligned on the data type field, please do the same here or update the others to match this style.

---

*[src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, line 680 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/160#-K_jGM2G7YIBCEosQcsn:-K_jGM2G7YIBCEosQcso:buu33b6) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/e27d07b442a80d54834d019bc6b9a5fd57020d49/src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala#L680)):*
> ```Scala
>       StructField("active_addons", ArrayType(buildAddonSchema, containsNull = false), nullable = true), // One per item in environment.addons.activeAddons
>       StructField("active_theme", buildAddonSchema, nullable = true), // environment.addons.theme
>       StructField("events", ArrayType(buildEventSchema, containsNull = false), nullable = true), // payload.processes.parent.events
> ```

Why is the new field added here? It should probably be added at the end of the row.

---

*[src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala, line 881 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/160#-K_jGT8Ec2sbj3HGXniT:-K_jGT8Ec2sbj3HGXniU:b-f2tqnk) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/e27d07b442a80d54834d019bc6b9a5fd57020d49/src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala#L881)):*
> ```Scala
>     MainSummaryView.getBrowserEngagement(jBogusScalars, "anything") should be (null)
>   }
>   "Events" can "be extracted" in {
> ```

nit: please add an empty line above this test

---

*[src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala, line 889 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/160#-K_jGW9Hfe3NEN-sxx_S:-K_jGW9Hfe3NEN-sxx_T:bhebplh) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/e27d07b442a80d54834d019bc6b9a5fd57020d49/src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala#L889)):*
> ```Scala
>            [81994404, "navigation", "search", "searchbar"],
>            ["malformed"]
>          ]""".stripMargin
> ```

You don't need `stripMargin` here, only need it if you do something like:
```scala
val events = parse(
      """[
        |  [533352, "navigation", "search", "urlbar", "enter", {"engine": "other-StartPage - English"}],
        |  [533352, "navigation", "search", "urlbar", "enter", {"engine": "other-StartPage - English"}, "random extra"],
        |  [85959, "navigation", "search", "urlbar", "enter"],
        |  [81994404, "navigation", "search", "searchbar"],
        |  ["malformed"]
        |]""".stripMargin
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/160#-:-K_jVv_-hOWSu4GT5P0s:b-n44n5e)*

**Comment by mreid-moz** [comment]
Oh, one other thing, please update the `MainSummary.md` docs with the new field/structure.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/160#-:-K_jzTTx8luycxE1kJSm:bzda11y)*

**Comment by sunahsuh** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, line 189 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/160#-K_jG271EjaV08lLqArd:-K_jzFhDv62j_FGLFaYl:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/e27d07b442a80d54834d019bc6b9a5fd57020d49/src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala#L189)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

nit: replace two spaces with one before the `=`
</blockquote></details>

Done.

---

*[src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, line 195 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/160#-K_jG5PrEM1AmgZznCv3:-K_jzJb1sEluhXKrGcmT:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/e27d07b442a80d54834d019bc6b9a5fd57020d49/src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala#L195)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

nit: remove the spaces before the colons here and below
</blockquote></details>

Done.

---

*[src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, line 563 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/160#-K_jITkB2A2YDQhKKppc:-K_jzK1bbfW0GdltPiIQ:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/e27d07b442a80d54834d019bc6b9a5fd57020d49/src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala#L563)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

Other sub-schemas are vertically aligned on the data type field, please do the same here or update the others to match this style.
</blockquote></details>

Done.

---

*[src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala, line 680 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/160#-K_jGM2G7YIBCEosQcsn:-K_jzq8HKF6huy26_mAX:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/e27d07b442a80d54834d019bc6b9a5fd57020d49/src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala#L680)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

Why is the new field added here? It should probably be added at the end of the row.
</blockquote></details>

Done.

---

*[src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala, line 881 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/160#-K_jGT8Ec2sbj3HGXniT:-K_k-KuUpjun4mUrSz9g:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/e27d07b442a80d54834d019bc6b9a5fd57020d49/src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala#L881)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

nit: please add an empty line above this test
</blockquote></details>

Done.

---

*[src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala, line 889 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/160#-K_jGW9Hfe3NEN-sxx_S:-K_k-PuO9EEfcw76unMc:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/e27d07b442a80d54834d019bc6b9a5fd57020d49/src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala#L889)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary><blockquote>

You don't need `stripMargin` here, only need it if you do something like:
```scala
val events = parse(
      """[
        |  [533352, "navigation", "search", "urlbar", "enter", {"engine": "other-StartPage - English"}],
        |  [533352, "navigation", "search", "urlbar", "enter", {"engine": "other-StartPage - English"}, "random extra"],
        |  [85959, "navigation", "search", "urlbar", "enter"],
        |  [81994404, "navigation", "search", "searchbar"],
        |  ["malformed"]
        |]""".stripMargin
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/160)*

**Comment by sunahsuh** [comment]
RFAL -- I snuck in a update for an old fieldname change that wasn't reflected in the docs in its own commit here too

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/160#-:-K_k2TQsTT7x2jyzckTW:b-xqp9cm)*

**Comment by mreid-moz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/160#-:-K_kD_yfbDqjrZyNXM29:bnfp4nl)*

**Pull request merged**
