### PR TITLE
Add scalars to the Longitudinal view

### PR DESCRIPTION
**Pull request by Dexterp37**
As described in bug 1288180, this adds both plain
and keyed scalars to the view and extends the test
coverage.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/120)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by Dexterp37** [comment]
r? @vitillo 

Should this be tested also by spawning a cluster and sending output to a test bucket? If that's the case, should I also check the content of the output parquet file (not sure how, though)?

**Comment by vitillo** [comment]
Yes, this should be tested on say a day or two of data and the output should be sent to telemetry-test-bucket. You can check the content of the output files simply by reading them back in with Spark.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/scalars/Scalars.scala, line 18 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KSkt_-SCWTZUT-Hbsty:-KSkt_-TAVHp8WycD_1x:b643oyv) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/2cbb87397f11ad1ed2304cebe3d96bc1b33d9d33/src/main/scala/com/mozilla/telemetry/scalars/Scalars.scala#L18)):*
> ```Scala
> }
> 
> object Scalars extends ScalarsDefinitionApi {
> ```

I am not sure I see why there is a need for a trait here.

---

*[src/main/scala/com/mozilla/telemetry/scalars/Scalars.scala, line 65 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KSkvwBxwY1puH5zyRYd:-KSkvwBxwY1puH5zyRYe:b-lu720v) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/2cbb87397f11ad1ed2304cebe3d96bc1b33d9d33/src/main/scala/com/mozilla/telemetry/scalars/Scalars.scala#L65)):*
> ```Scala
>       }
> 
>       (key, scalarDefinitions.flatten.toMap)
> ```

If we throw away the key right after, why are we returning it in the first place?

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 713 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KSkwrYvasGnxZFm_1pO:-KSkwrYwBuks7kx8LPIv:brdbn8b) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/2cbb87397f11ad1ed2304cebe3d96bc1b33d9d33/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L713)):*
> ```Scala
> 
>   private def vectorizeScalar_[T:ClassTag](name: String,
>                                               payloads: List[Map[String, AnyVal]],
> ```

Please indent the parameters correctly.

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 729 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KSkx4ZFBperj6cTwq83:-KSkx4ZFBperj6cTwq84:b-ym0z3q) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/2cbb87397f11ad1ed2304cebe3d96bc1b33d9d33/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L729)):*
> ```Scala
> 
>   private def vectorizeScalar[T:ClassTag](name: String,
>                                             definition: ScalarDefinition,
> ```

Please indent parameters correctly.

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 756 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KSky_eNxm-6HH5m0BI4:-KSky_eOUN-LjTVwfLCq:bdeipxa) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/2cbb87397f11ad1ed2304cebe3d96bc1b33d9d33/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L756)):*
> ```Scala
>     // Get a list of the scalars in the ping.
>     val scalarList = payloads.map{ case (x) =>
>       val json = x.getOrElse("payload.processes.parent.scalars", return).asInstanceOf[String]
> ```

I don't think this looks right, i.e. I doubt Heka files have that section outside from the payload; you might want to confirm with trink or mreid. What about non parent scalars though?

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 781 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KSkxXy78CLj5dxSn6EE:-KSkxXy78CLj5dxSn6EF:b-7y4e1s) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/2cbb87397f11ad1ed2304cebe3d96bc1b33d9d33/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L781)):*
> ```Scala
> 
>     val scalarsList = payloads.map{ case (x) =>
>       val json = x.getOrElse("payload.processes.parent.keyedScalars", return).asInstanceOf[String]
> ```

I don't think this looks right, i.e. I doubt Heka files have that section outside from the payload. What about non parent scalars though? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-:-KSkrcEulXtA7IJEVmmq:b-quupmq)*

**Comment by Dexterp37** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/scalars/Scalars.scala, line 18 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KSkt_-SCWTZUT-Hbsty:-KSlJPWzMUeGhQekiu2_:bsx260p) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/2cbb87397f11ad1ed2304cebe3d96bc1b33d9d33/src/main/scala/com/mozilla/telemetry/scalars/Scalars.scala#L18)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> I am not sure I see why there is a need for a trait here.
</details>
That's only for testing purposes: in the LongitudinalTest a mock API provider implements this trait to provide fake scalar definitions.

---

*[src/main/scala/com/mozilla/telemetry/scalars/Scalars.scala, line 65 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KSkvwBxwY1puH5zyRYd:-KSlM4tGNvk64gSK_Txr:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/2cbb87397f11ad1ed2304cebe3d96bc1b33d9d33/src/main/scala/com/mozilla/telemetry/scalars/Scalars.scala#L65)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> If we throw away the key right after, why are we returning it in the first place?
</details>
Done.

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 713 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KSkwrYvasGnxZFm_1pO:-KSlIu51RHnka37Twedw:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/2cbb87397f11ad1ed2304cebe3d96bc1b33d9d33/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L713)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Please indent the parameters correctly.
</details>
Done.

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 729 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KSkx4ZFBperj6cTwq83:-KSlIwvwtTKmSckywA3R:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/2cbb87397f11ad1ed2304cebe3d96bc1b33d9d33/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L729)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Please indent parameters correctly.
</details>
Done.

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 756 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KSky_eNxm-6HH5m0BI4:-KSlT6Q3UQD_PCdKmLJh:b1e7dsb) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/2cbb87397f11ad1ed2304cebe3d96bc1b33d9d33/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L756)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> I don't think this looks right, i.e. I doubt Heka files have that section outside from the payload; you might want to confirm with trink or mreid. What about non parent scalars though?
</details>
I just confirmed with @mreid-moz that that section isn't outside from the payload. As of now, non-parent scalars are not supported on the client. It seems to me that this is also the case for non-parent histograms, that are stored in [payload.processes.content.*](https://dxr.mozilla.org/mozilla-central/rev/66a77b9bfe5dcacd50eccf85de7c0e7e15ce0ffd/toolkit/components/telemetry/TelemetrySession.jsm#1300-1301).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120)*

**Comment by mreid-moz** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 756 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KSky_eNxm-6HH5m0BI4:-KSlVy0vOMlu4uELOkHt:b-f5y5ru) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/2cbb87397f11ad1ed2304cebe3d96bc1b33d9d33/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L756)):*
<details><summary><i>Previously, Dexterp37 (Alessio Placitelli) wrote…</i></summary>
> I just confirmed with @mreid-moz that that section isn't outside from the payload. As of now, non-parent scalars are not supported on the client. It seems to me that this is also the case for non-parent histograms, that are stored in [payload.processes.content.*](https://dxr.mozilla.org/mozilla-central/rev/66a77b9bfe5dcacd50eccf85de7c0e7e15ce0ffd/toolkit/components/telemetry/TelemetrySession.jsm#1300-1301).
</details>
The scalar info is not split out of the payload. The most straightforward change would probably be to modify [this line](https://github.com/mozilla/telemetry-batch-view/blob/master/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L140) to return the full Heka Message (instead of just the `fields` map), then you could pull out the fields in the `buildRecord` function as well as having access to the the `Payload` JSON.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120)*

**Comment by vitillo** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/scalars/Scalars.scala, line 18 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KSkt_-SCWTZUT-Hbsty:-KSqP78Hnu8QnE035kgL:b-ip79k5) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/2cbb87397f11ad1ed2304cebe3d96bc1b33d9d33/src/main/scala/com/mozilla/telemetry/scalars/Scalars.scala#L18)):*
<details><summary><i>Previously, Dexterp37 (Alessio Placitelli) wrote…</i></summary>
> That's only for testing purposes: in the LongitudinalTest a mock API provider implements this trait to provide fake scalar definitions.
</details>
What about getting rid of the object and use a package object with a `definitions` variable? In the tests then all you have to do is to define your own `definitions` variable. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120)*

**Comment by Dexterp37** [comment]
I just checked on a new shiny EMR5.0.0 cluster: after loading the parquet file, I'm able to see the following definitions in the schema:

> StructField(scalar_browser_engagement_max_concurrent_tab_count,ArrayType(LongType,true),true), 
> StructField(scalar_browser_engagement_window_open_event_count,ArrayType(LongType,true),true), 
> StructField(scalar_browser_engagement_tab_open_event_count,ArrayType(LongType,true),true), 
> StructField(scalar_browser_engagement_max_concurrent_window_count,ArrayType(LongType,true),true), 
> StructField(scalar_browser_engagement_total_uri_count,ArrayType(LongType,true),true), 
> StructField(scalar_browser_engagement_unique_domains_count,ArrayType(LongType,true),true))

Querying the longitudinal seems to confirm that the data is there:

> scala> val tst = spark.sql("select scalar_browser_engagement_max_concurrent_tab_count as the_scalar FROM scalars").where("scalar_browser_engagement_max_concurrent_tab_count is not null")
> scala> tst.show
> +--------------------+
> |          the_scalar|
> +--------------------+
> |     [1, 1, 4, 2, 6]|
> |        [3, 3, 2, 3]|
> |           [1, 1, 3]|
> |           [5, 6, 2]|
> |        [2, 3, 4, 5]|
> |        [4, 3, 1, 1]|
> |          [5, 4, 12]|
> |                 [3]|
> |              [2, 4]|
> |              [5, 2]|
> |     [5, 2, 5, 6, 6]|
> |           [8, 0, 0]|
> |       [23, 0, 0, 0]|
> |      [16, 1, 0, 17]|
> |           [2, 1, 0]|
> |[1, 1, 2, 2, 1, 1...|
> |              [3, 2]|
> |     [2, 2, 2, 2, 2]|
> |     [1, 1, 4, 1, 3]|
> |        [1, 1, 1, 1]|
> +--------------------+
> only showing top 20 rows

Done.

---

Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/scalars/Scalars.scala, line 18 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KSkt_-SCWTZUT-Hbsty:-KSrwM-fvObF42DizIK6:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/2cbb87397f11ad1ed2304cebe3d96bc1b33d9d33/src/main/scala/com/mozilla/telemetry/scalars/Scalars.scala#L18)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> What about getting rid of the object and use a package object with a `definitions` variable? In the tests then all you have to do is to define your own `definitions` variable. 
</details>
Done.

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 756 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KSky_eNxm-6HH5m0BI4:-KSrwQSvOe109l7ibnEI:b3jgalh) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/2cbb87397f11ad1ed2304cebe3d96bc1b33d9d33/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L756)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>
> The scalar info is not split out of the payload. The most straightforward change would probably be to modify [this line](https://github.com/mozilla/telemetry-batch-view/blob/master/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L140) to return the full Heka Message (instead of just the `fields` map), then you could pull out the fields in the `buildRecord` function as well as having access to the the `Payload` JSON.
</details>
I've added the ping payload to the "payload" property of the message. Now I'm able to parse it from here.

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 781 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KSkxXy78CLj5dxSn6EE:-KSrwfHd7lyQW7UMpo7R:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/2cbb87397f11ad1ed2304cebe3d96bc1b33d9d33/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L781)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> I don't think this looks right, i.e. I doubt Heka files have that section outside from the payload. What about non parent scalars though? 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-:-KSrv30bOGTbQdW_nQyF:bei1ybp)*

**Comment by Dexterp37** [comment]
This is ready for a new pass. r?@vitillo

---

Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-:-KSuh-ZEgiyTgZvVexcu:b-2k6kil)*

**Comment by vitillo** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 756 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KT9hLwvi8JDtLKYVPun:-KT9hLwvi8JDtLKYVPuo:b-svi8qc) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/28fce46ca09422d0e90e82cff0509c5321b9c07e/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L756)):*
> ```Scala
>     // Get a list of the scalars in the ping.
>     val scalarList = payloads.map{ case (x) =>
>       val fullJson = x.getOrElse("payload", return).asInstanceOf[String]
> ```

nit: s/fullJson/payload

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 757 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KT9iPJwvo6fKIAyaKCW:-KT9iPJwvo6fKIAyaKCX:b8g7s9z) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/28fce46ca09422d0e90e82cff0509c5321b9c07e/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L757)):*
> ```Scala
>     val scalarList = payloads.map{ case (x) =>
>       val fullJson = x.getOrElse("payload", return).asInstanceOf[String]
>       (parse(fullJson) \\ "scalars").toOption match {
> ```

I am not sure I understand how/where you are accessing `processes.parent` now.

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 782 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KT9hWLCNdd1q9JFSkMn:-KT9hWLCNdd1q9JFSkMo:b8e7x4v) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/28fce46ca09422d0e90e82cff0509c5321b9c07e/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L782)):*
> ```Scala
> 
>     val scalarsList = payloads.map{ case (x) =>
>       val fullJson = x.getOrElse("payload", return).asInstanceOf[String]
> ```

nit: s/fullJson/payload

I don't particularly like that we are doing the parsing of the whole payload twice though. Maybe we can avoid that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120)*

**Comment by Dexterp37** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 756 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KT9hLwvi8JDtLKYVPun:-KT9omfMYtoULSUhQ0cH:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/28fce46ca09422d0e90e82cff0509c5321b9c07e/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L756)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> nit: s/fullJson/payload
</details>
Done.

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 757 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KT9iPJwvo6fKIAyaKCW:-KTAi09m0oxe4R6Jxo0-:bs6a5p9) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/28fce46ca09422d0e90e82cff0509c5321b9c07e/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L757)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> I am not sure I understand how/where you are accessing `processes.parent` now.
</details>
I made it more explicit in the current release. Done.

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 782 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KT9hWLCNdd1q9JFSkMn:-KT9onXJmE73ElDu8pjA:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/28fce46ca09422d0e90e82cff0509c5321b9c07e/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L782)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> nit: s/fullJson/payload
> 
> I don't particularly like that we are doing the parsing of the whole payload twice though. Maybe we can avoid that.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120)*

**Comment by vitillo** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 782 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KT9hWLCNdd1q9JFSkMn:-KTEalCr-KQtv_TbgwdB:b8box5c) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/28fce46ca09422d0e90e82cff0509c5321b9c07e/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L782)):*
<details><summary><i>Previously, Dexterp37 (Alessio Placitelli) wrote…</i></summary>
> Done.
</details>
Parsing is still done twice and should be avoided.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120)*

**Comment by Dexterp37** [comment]
The new version seems to work as expected! I ran the longitudinal and I'm able to query the scalars as shown below:

> scala>  val tst = spark.sql("select scalar_parent_browser_engagement_max_concurrent_tab_count as the_scalar FROM scalars").where("scalar_parent_browser_engagement_max_concurrent_tab_count is not null")
> tst: org.apache.spark.sql.Dataset[org.apache.spark.sql.Row] = [the_scalar: array<bigint>]
> 
> scala> tst.show
> +--------------------+
> |          the_scalar|
> +--------------------+
> |              [1, 1]|
> |                 [2]|
> |[3, 3, 4, 1, 2, 3...|
> |              [1, 1]|
> |           [1, 1, 1]|
> |                 [1]|
> |[1, 1, 1, 1, 1, 1...|
> |          [11, 4, 5]|
> |     [1, 1, 1, 1, 6]|
> |           [1, 2, 4]|
> |        [1, 1, 1, 1]|
> |              [3, 3]|
> |[1, 2, 2, 2, 3, 2...|
> |              [3, 2]|
> |[2, 6, 3, 1, 0, 1...|
> |     [3, 2, 3, 3, 3]|
> |       [11, 7, 5, 3]|
> |           [2, 1, 1]|
> |                [12]|
> |           [2, 1, 2]|
> +--------------------+
> only showing top 20 rows

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 782 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-KT9hWLCNdd1q9JFSkMn:-KTEi-o3APBRK6gA9sKl:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/28fce46ca09422d0e90e82cff0509c5321b9c07e/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L782)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Parsing is still done twice and should be avoided.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-:-KTEh_WZJ0Yc4lKIhOhh:b-5hvqye)*

**Comment by vitillo** [comment]
Nice work!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/120#-:-KTEkb9rDZl0n-MMzd70:bdtx8r6)*

**Comment by mreid-moz** [comment]
Cool! It would be a good idea to add an example query to the [Longitudinal Examples](https://wiki.mozilla.org/Telemetry/LongitudinalExamples) wiki page.

**Pull request merged**
