### PR TITLE
Use the Telemetry lib instead of getRecords()

### PR DESCRIPTION
**Pull request by Uberi**
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1275025

### CODE REVIEW

**Comment by vitillo** [comment]
r+

**Comment by vitillo** [comment]
@Uberi I reverted this change as I noticed a possible bug only later and I assume this had been tested on real data. I think what you want is `Telemetry.getMessages` and not `Telemetry.getRecords`.

**Comment by vitillo** [comment]
@Uberi could you file a new PR and mention if change has been tested with real data? Thanks.

**Comment by Uberi** [comment]
Sure, I'll be able to give it a test after https://bugzilla.mozilla.org/show_bug.cgi?id=1275986 is resolved.

**Pull request merged**
