### PR TITLE
Bug 1269466 - Add push_notification_received field to ClientCountView

### PR DESCRIPTION
**Pull request by sunahsuh**
The push_notification_received indicates whether a user has received a web notification or a popup notification in the session. This field will be used to create an ER dashboard per bug #1269466

Note I took a bit of a license with the PopupNotificationStatsDummyType in the tests since only null/not null is necessary to compute the field

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/121)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by vitillo** [comment]
Please rebase to a single commit; you might also want to have a look at our [guidelines for commits](https://github.com/mozilla/telemetry-onboarding/blob/master/Contributing.md).

**Comment by vitillo** [comment]
Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/ClientCountView.scala, line 39 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/121#-KSuZjNAa0YqciFWRT4r:-KSuZjNBgSXOMn7Q5AYD:b-kuukrn) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/23a2780a47d5990d0301a974973e30314c4f108a/src/main/scala/com/mozilla/telemetry/views/ClientCountView.scala#L39)):*
> ```Scala
>     "devtools_toolbox_opened_count > 0 as devtools_toolbox_opened" ::
>     "loop_activity_counter.open_panel > 0 as loop_activity_open_panel" ::
>     "popup_notification_stats is not null or web_notification_shown > 0 as push_notification_user" ::
> ```

I don't think `popup_notification_stats is not null` is correct as a popup notification might have been generated by something that has nothing to do with Push. I think what we want here is to check that the keyed histogram contains the key for the Push Permission Dialog. You might want to double check with Bryan.

---

*[src/test/scala/com/mozilla/telemetry/ClientCountViewTest.scala, line 19 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/121#-KSuVwe9Es8OCozxPMaD:-KSuVweA5UPESc1ZtRlK:b-gl3vkq) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/23a2780a47d5990d0301a974973e30314c4f108a/src/test/scala/com/mozilla/telemetry/ClientCountViewTest.scala#L19)):*
> ```Scala
> 
> // popupNotificationStats type is 22 separate int fields -- simplifying down for this test
> case class PopupNotificationStatsDummyType(dummy_field: Int)
> ```

You could declare this as `PopupNotificationStatsType(offered: Int)` and leave the comment as is.

---

*[src/test/scala/com/mozilla/telemetry/ClientCountViewTest.scala, line 35 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/121#-KSuWtrMSmymVPwVMiDL:-KSuWtrNR5Is2BHqHPHN:b-ez2l1m) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/23a2780a47d5990d0301a974973e30314c4f108a/src/test/scala/com/mozilla/telemetry/ClientCountViewTest.scala#L35)):*
> ```Scala
>                       devtools_toolbox_opened_count: Int,
>                       loop_activity_counter: LoopActivity,
>                       popup_notification_stats: Option[PopupNotificationStatsDummyType],
> ```

This doesn't match the type declared [here](https://github.com/mozilla/telemetry-batch-view/blob/master/src/main/scala/com/mozilla/telemetry/views/MainSummaryView.scala#L517) (it's a keyed histogram).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/121)*

**Comment by vitillo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/ClientCountView.scala, line 39 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/121#-KSuZjNAa0YqciFWRT4r:-KSua5m0U0IXNPmLABzI:b-jnydew) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/23a2780a47d5990d0301a974973e30314c4f108a/src/main/scala/com/mozilla/telemetry/views/ClientCountView.scala#L39)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> I don't think `popup_notification_stats is not null` is correct as a popup notification might have been generated by something that has nothing to do with Push. I think what we want here is to check that the keyed histogram contains the key for the Push Permission Dialog. You might want to double check with Bryan.
</details>
If what I am saying is correct you might want to redo the math to determine the error for the HLL intersection to check if it's still OK to proceed with this approach.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/121)*

**Comment by sunahsuh** [comment]
After investigating the issue roberto raised about `popup_notification_stats is not null` not being the correct measure, the actual number of qualifying push users is too small to use HLL since it's within the standard error for the population count. Closing this PR in favor of trying to do this with a sample of main_summary.

**Pull request closed without merging**
