### PR TITLE
Bug 1310673 - Filter out content crash pings from crash aggregates

### PR DESCRIPTION
**Pull request by maurodoglio**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/130)

### CODE REVIEW

**Comment by vitillo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala, line 196 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/130#-KUrLHOD2gXyVYeXbDhO:-KUrLHOEttuGJ3z7l8ZD:b-mrp3oa) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/6a235b10754e254d2e253ff4dad89244cedecfb9/src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala#L196)):*
> ```Scala
> 
>     (records, mainProcessedAccumulator, mainIgnoredAccumulator,
>       crashProcessedAccumulator, crashIgnoredAccumulator, contentCrashIgnoredAccumulator)
> ```

This doesn't look indented correctly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/130)*

**Comment by maurodoglio** [comment]
Ready for another look

**Comment by maurodoglio** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala, line 196 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/130#-KUrLHOD2gXyVYeXbDhO:-KVAxgCHSFSDws5yxBd3:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/6a235b10754e254d2e253ff4dad89244cedecfb9/src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala#L196)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> This doesn't look indented correctly.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/130)*

**Comment by vitillo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/130#-:-KVQ1G5LJDjxJ5vr--Wv:bnfp4nl)*

**Pull request merged**
