### PR TITLE
Store the AddonRecommender model to S3

### PR DESCRIPTION
**Pull request by Dexterp37**
This also fixes the breakage due to the introduction
of the is_system property for the active_addons.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/101)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by Dexterp37** [comment]
r? @vitillo 

Please note that I left the HDFS model copying code there to ease debugging if we are to run the job manually. But can remove that part if desired (and get rid of the ugly try{}catch block there..).

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 135 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/101#-KPHzMFHv94F7f7oQIq9:-KPHzMFHv94F7f7oQIqA:b41sbqk) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/430c12b3bf5ddb9f95152d6d4e41e58b3e437074/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L135)):*
> ```Scala
> 
>     val hadoopConf = sc.hadoopConfiguration
>     hadoopConf.set("fs.s3n.impl", "org.apache.hadoop.fs.s3native.NativeS3FileSystem")
> ```

I don't think the above two lines are necessary.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 137 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/101#-KPHz5YeHVL6HZFpWK1c:-KPHz5YeHVL6HZFpWK1d:b-pcjcek) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/430c12b3bf5ddb9f95152d6d4e41e58b3e437074/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L137)):*
> ```Scala
>     hadoopConf.set("fs.s3n.impl", "org.apache.hadoop.fs.s3native.NativeS3FileSystem")
> 
>     val fmt = format.DateTimeFormat.forPattern("yyyyMMdd")
> ```

Let's do the parameter validation in the `main` method.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 143 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/101#-KPHzZklAlUlT7ObBe8a:-KPHzZklAlUlT7ObBe8b:b-9menbp) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/430c12b3bf5ddb9f95152d6d4e41e58b3e437074/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L143)):*
> ```Scala
>     }
> 
>     val s3prefix = s"telemetry-ml/addon_recommender/${date}"
> ```

Why is the bucket set to `telemetry-ml`? I think it should be set to `outputBucket`.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 144 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/101#-KPI-2W86W0PhgGoSx7C:-KPI-2W910n273kRFh9X:bl9ojn4) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/430c12b3bf5ddb9f95152d6d4e41e58b3e437074/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L144)):*
> ```Scala
> 
>     val s3prefix = s"telemetry-ml/addon_recommender/${date}"
>     require(S3Store.isPrefixEmpty(outputBucket, s3prefix), s"s3://${outputBucket}/${s3prefix} already exists!")
> ```

It probably makes sense to overwrite the data. Otherwise, if the job crashes while the data is being stored and Airflow retriggers it, it will keep failing until someone manually removes the incomplete data from S3.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/101)*

**Comment by Dexterp37** [comment]
r? @vitillo

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 143 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/101#-KPHzZklAlUlT7ObBe8a:-KPIMZp-abYm_b9PnaKx:bwsjsu5) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/430c12b3bf5ddb9f95152d6d4e41e58b3e437074/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L143)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Why is the bucket set to `telemetry-ml`? I think it should be set to `outputBucket`.
</details>
The outputBucket is passed as a distinct argument of S3Store.uploadFile, when saving the addon mapping and item matrix. That function also requires a "prefix" and a "file name", that are combined to build the S3 key.

When saving the model, we chain the outputBucket and s3prefix together.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/101#-:-KPEHeOi3ktq7GYfIuO-:b-hajsbv)*

**Comment by vitillo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 143 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/101#-KPHzZklAlUlT7ObBe8a:-KPIXJHNqNUEjnKYT4ib:b5zk08x) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/430c12b3bf5ddb9f95152d6d4e41e58b3e437074/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L143)):*
<details><summary><i>Previously, Dexterp37 (Alessio Placitelli) wrote…</i></summary>
> The outputBucket is passed as a distinct argument of S3Store.uploadFile, when saving the addon mapping and item matrix. That function also requires a "prefix" and a "file name", that are combined to build the S3 key.
> 
> When saving the model, we chain the outputBucket and s3prefix together.
</details>
I meant that we have on S3 a bucket called `telemetry-ml` but that might change in the future. You should store the data under `s3://$outputBucket/addon_recommender/$date`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/101)*

**Comment by Dexterp37** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 143 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/101#-KPHzZklAlUlT7ObBe8a:-KPImI_5UfSb1AqOjhjh:b1xzwco) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/430c12b3bf5ddb9f95152d6d4e41e58b3e437074/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L143)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> I meant that we have on S3 a bucket called `telemetry-ml` but that might change in the future. You should store the data under `s3://$outputBucket/addon_recommender/$date`.
</details>
I've changed that as discussed over IRC. We're now saving all the generated data (JSON, the model) to the private bucket. The JSON files are also mirrored on the public bucket so that services like AMO can access them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/101)*

**Comment by Dexterp37** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 135 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/101#-KPHzMFHv94F7f7oQIq9:-KPIn_ttTjZS7VzmNgkd:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/430c12b3bf5ddb9f95152d6d4e41e58b3e437074/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L135)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> I don't think the above two lines are necessary.
</details>
Done.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 137 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/101#-KPHz5YeHVL6HZFpWK1c:-KPInfe-K9QcwhaWdkE-:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/430c12b3bf5ddb9f95152d6d4e41e58b3e437074/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L137)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Let's do the parameter validation in the `main` method.
</details>
Done.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 144 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/101#-KPI-2W86W0PhgGoSx7C:-KPInf2Lhv6VSUGf5HgT:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/430c12b3bf5ddb9f95152d6d4e41e58b3e437074/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L144)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> It probably makes sense to overwrite the data. Otherwise, if the job crashes while the data is being stored and Airflow retriggers it, it will keep failing until someone manually removes the incomplete data from S3.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/101)*

**Comment by Dexterp37** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 137 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/101#-KPHz5YeHVL6HZFpWK1c:-KPInq4hDynfi6O7MAcw:b32w0x) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/430c12b3bf5ddb9f95152d6d4e41e58b3e437074/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L137)):*
<details><summary><i>Previously, Dexterp37 (Alessio Placitelli) wrote…</i></summary>
> Done.
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/101)*

**Comment by vitillo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/101#-:-KPIoYy6y97C0SlTSsib:bnfp4nl)*

**Pull request merged**
