### PR TITLE
Refactor agg functions to a separate package

### PR DESCRIPTION
**Pull request by harterrt**
Moved XSec generator functions into class methods and constructors.
Separated Aggregate object into it's own context. Split aggregation into
it's own package

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/109)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by harterrt** [comment]
@vitillo, PTAL

**Comment by vitillo** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/utils/Aggregation.scala, line 3 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/109#-KREsgwrQV2Sn2UcEdlG:-KREsgwslNiYoJ1uvNVj:b-ykj4zg) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/572c585155d045129ce28b218cb974ece777cb37/src/main/scala/com/mozilla/telemetry/utils/Aggregation.scala#L3)):*
> ```Scala
> package com.mozilla.telemetry.utils
> 
> object Aggregation {
> ```

What about creating a package called `aggregation` and define the methods within a package object? 

---

*[src/main/scala/com/mozilla/telemetry/utils/Aggregation.scala, line 4 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/109#-KREsVZKjFqY6aZgWo41:-KREsVZKjFqY6aZgWo42:b-xsbkyd) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/572c585155d045129ce28b218cb974ece777cb37/src/main/scala/com/mozilla/telemetry/utils/Aggregation.scala#L4)):*
> ```Scala
> 
> object Aggregation {
>   def weightedMode(values: Seq[String], weights: Seq[Long]): String = {
> ```

There is no real need for values to be of type String; what about making this method generic?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/109)*

**Comment by harterrt** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/utils/Aggregation.scala, line 3 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/109#-KREsgwrQV2Sn2UcEdlG:-KRpiV9sn4s09BaOfWUY:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/572c585155d045129ce28b218cb974ece777cb37/src/main/scala/com/mozilla/telemetry/utils/Aggregation.scala#L3)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> What about creating a package called `aggregation` and define the methods within a package object? 
</details>
Done.

---

*[src/main/scala/com/mozilla/telemetry/utils/Aggregation.scala, line 4 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/109#-KREsVZKjFqY6aZgWo41:-KRpgDJUGVcKHVQdi63X:b-is5zrg) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/572c585155d045129ce28b218cb974ece777cb37/src/main/scala/com/mozilla/telemetry/utils/Aggregation.scala#L4)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> There is no real need for values to be of type String; what about making this method generic?
</details>
Good catch, I changed this in a PR coming soon. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/109)*

**Comment by harterrt** [comment]
@vitillo RFAL. Thanks!

---

Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/109#-:-KRpmvi1sdu0hf90aaMZ:b-ltf9bh)*

**Comment by vitillo** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/109#-:-KS17kC9eLNiJSTzEAYE:bnfp4nl)*

**Pull request merged**
