### PR TITLE
Bug 1290181 - Add Addons data to main summary 

### PR DESCRIPTION
**Pull request by mreid-moz**
This also incorporates Bug 1300224 for the Addons data itself.

---

This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/134)

### CODE REVIEW

**Comment by vitillo** [comment]
Reviewed 2 of 2 files at r1, 5 of 5 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[docs/Addons.md, line 4 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KV_AZDW93XdbPUotZIr:-KV_AZDXmgrc62sR3SQ6:bsj4od6) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/159c767bac11d62ea7b11112b289b3f71bfb185b/docs/Addons.md#L4)):*
> ```Markdown
> ==================
> 
> The Addons dataset is generated by `src/main/scala/com/mozilla/telemetry/views/AddonsView.scala`. It contains one or more records for every [Main Summary](MainSummary.md) record that contains a non-null value for client_id. Each Addons record contains info for a single addon, or if the main ping did not contain any active addons, there will be a row with nulls for all the addon fields (to identify client_ids/records without any addons).
> ```

Why do we need an add-on dataset if we have the same data in the main summary now?

---

*[src/main/scala/com/mozilla/telemetry/views/AddonsView.scala, line 67 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KV_Adw-xeOvnjvVztmC:-KV_Adw-xeOvnjvVztmD:b-lodwcn) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/159c767bac11d62ea7b11112b289b3f71bfb185b/src/main/scala/com/mozilla/telemetry/views/AddonsView.scala#L67)):*
> ```Scala
> 
>       println("=======================================================================================")
>       println(s"BEGINNING JOB $jobName $streamVersion FOR $currentDateString")
> ```

`streamVersion` is a misnomer I think.

---

*[src/main/scala/com/mozilla/telemetry/views/AddonsView.scala, line 93 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KV_AuML4AoH18SYkKjg:-KV_AuML4AoH18SYkKjh:b-zhe2zj) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/159c767bac11d62ea7b11112b289b3f71bfb185b/src/main/scala/com/mozilla/telemetry/views/AddonsView.scala#L93)):*
> ```Scala
>     val addonSchema = MainSummaryView.buildAddonSchema
>     val records = mainSummaryData.select("document_id", "client_id", "sample_id",
>       "subsession_start_date", "active_addons")
> ```

Please fix indentation.

---

*[src/main/scala/com/mozilla/telemetry/views/AddonsView.scala, line 103 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KV_ASo_R2IZkzdxudq8:-KV_ASo_R2IZkzdxudq9:b-8pklxt) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/159c767bac11d62ea7b11112b289b3f71bfb185b/src/main/scala/com/mozilla/telemetry/views/AddonsView.scala#L103)):*
> ```Scala
>         .otherwise(array(lit(null).cast(addonSchema)))))
> 
>     exploded.selectExpr("document_id", "client_id", "sample_id", "subsession_start_date",
> ```

Please use the same indentation style everywhere.

---

*[src/test/scala/com/mozilla/telemetry/AddonsViewTest.scala, line 8 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KV_B7W73oN25VE0Vqhy:-KV_B7W73oN25VE0Vqhz:b-3dkkye) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/159c767bac11d62ea7b11112b289b3f71bfb185b/src/test/scala/com/mozilla/telemetry/AddonsViewTest.scala#L8)):*
> ```Scala
> import org.scalatest.{FlatSpec, Matchers}
> 
> case class Addon(addon_id: String,
> ```

Let's try to use the same class everywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134)*

**Comment by mreid-moz** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[docs/Addons.md, line 4 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KV_AZDW93XdbPUotZIr:-KV_NehAkxdLfg0i_eI2:beva2tx) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/159c767bac11d62ea7b11112b289b3f71bfb185b/docs/Addons.md#L4)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Why do we need an add-on dataset if we have the same data in the main summary now?
</details>
The idea is for people to be able to do addon-oriented queries without having to do the "explode" part (which is kind of a pain if you want to include records for empty / null addon rows) every time. Basically a materialized view for the exploded addons data. If one doesn't need any of the extra fields in `main_summary`, then that should simplify some basic addon-oriented queries.

---

*[src/main/scala/com/mozilla/telemetry/views/AddonsView.scala, line 67 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KV_Adw-xeOvnjvVztmC:-KV_O54aDx6qFJE6aZyW:bsu6dg7) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/159c767bac11d62ea7b11112b289b3f71bfb185b/src/main/scala/com/mozilla/telemetry/views/AddonsView.scala#L67)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> `streamVersion` is a misnomer I think.
</details>
It is, it's a holdover from back when MainSummary was a "stream" rather than a "view".  How about `jobVersion` instead?

---

*[src/main/scala/com/mozilla/telemetry/views/AddonsView.scala, line 93 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KV_AuML4AoH18SYkKjg:-KV_OJVGOq8mL_lG_ziE:b-2pudfl) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/159c767bac11d62ea7b11112b289b3f71bfb185b/src/main/scala/com/mozilla/telemetry/views/AddonsView.scala#L93)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Please fix indentation.
</details>
This is how my IDE automatically formats it - would you prefer it aligned under `"document_id"`?

---

*[src/main/scala/com/mozilla/telemetry/views/AddonsView.scala, line 103 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KV_ASo_R2IZkzdxudq8:-KV_W2UPrXWhwYSidqUN:b-4pilu0) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/159c767bac11d62ea7b11112b289b3f71bfb185b/src/main/scala/com/mozilla/telemetry/views/AddonsView.scala#L103)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Please use the same indentation style everywhere.
</details>
I'll fix

---

*[src/test/scala/com/mozilla/telemetry/AddonsViewTest.scala, line 8 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KV_B7W73oN25VE0Vqhy:-KV_iLk9CUqU1mXoW5U5:bcfqsmk) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/159c767bac11d62ea7b11112b289b3f71bfb185b/src/test/scala/com/mozilla/telemetry/AddonsViewTest.scala#L8)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Let's try to use the same class everywhere.
</details>
Is there a way to use a single class for both `camelCase` and `snake_case` variants of field names?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134)*

**Comment by vitillo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/AddonsView.scala, line 67 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KV_Adw-xeOvnjvVztmC:-KVaFTShiqh4dkJg5J9C:b-4w8b3h) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/159c767bac11d62ea7b11112b289b3f71bfb185b/src/main/scala/com/mozilla/telemetry/views/AddonsView.scala#L67)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>
> It is, it's a holdover from back when MainSummary was a "stream" rather than a "view".  How about `jobVersion` instead?
</details>
Maybe `schemaVersion`?

---

*[src/main/scala/com/mozilla/telemetry/views/AddonsView.scala, line 93 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KV_AuML4AoH18SYkKjg:-KVaFasphSw9FtInIK9K:bo6ompy) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/159c767bac11d62ea7b11112b289b3f71bfb185b/src/main/scala/com/mozilla/telemetry/views/AddonsView.scala#L93)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>
> This is how my IDE automatically formats it - would you prefer it aligned under `"document_id"`?
</details>
Yes please.

---

*[src/test/scala/com/mozilla/telemetry/AddonsViewTest.scala, line 8 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KV_B7W73oN25VE0Vqhy:-KVaFdkRWkBoSF2FbY0A:b-wtpjt4) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/159c767bac11d62ea7b11112b289b3f71bfb185b/src/test/scala/com/mozilla/telemetry/AddonsViewTest.scala#L8)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>
> Is there a way to use a single class for both `camelCase` and `snake_case` variants of field names?
</details>
I don't think so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134)*

**Comment by mreid-moz** [comment]
Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/AddonsView.scala, line 67 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KV_Adw-xeOvnjvVztmC:-KVaJtR6uL5-UhUBWfE3:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/159c767bac11d62ea7b11112b289b3f71bfb185b/src/main/scala/com/mozilla/telemetry/views/AddonsView.scala#L67)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Maybe `schemaVersion`?
</details>
Done.

---

*[src/main/scala/com/mozilla/telemetry/views/AddonsView.scala, line 93 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KV_AuML4AoH18SYkKjg:-KVaJuXE6Sfdi-RizoCL:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/159c767bac11d62ea7b11112b289b3f71bfb185b/src/main/scala/com/mozilla/telemetry/views/AddonsView.scala#L93)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Yes please.
</details>
Done.

---

*[src/test/scala/com/mozilla/telemetry/AddonsViewTest.scala, line 8 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KV_B7W73oN25VE0Vqhy:-KVaOzs36AKXJX4PWDmi:b1wwwdd) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/159c767bac11d62ea7b11112b289b3f71bfb185b/src/test/scala/com/mozilla/telemetry/AddonsViewTest.scala#L8)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> I don't think so.
</details>
As I see it, there are actually 3 different `Addon` classes in use:
- The one used to parse the incoming JSON, which uses camelCase and all fields are optional
- The one used to create literal structs for use in the Addon tests, which uses snake_case and no fields are optional (but they are nullable)
- The one used in the cross-sectional dataset, which uses snake_case and all fields are optional.

I'm not sure how to combine these without adding even more code. Can we address this in a follow-up?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134)*

**Comment by vitillo** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/AddonsView.scala, line 94 at r5](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KVeiXE8bMTwg0hKEW8n:-KVeiXE8bMTwg0hKEW8o:b41dx85) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/9df6ececd520a790d6576c8b56b2f0e0713c0745/src/main/scala/com/mozilla/telemetry/views/AddonsView.scala#L94)):*
> ```Scala
>     val records = mainSummaryData.select("document_id", "client_id", "sample_id",
>                                          "subsession_start_date", "active_addons")
>                                          .where("client_id is not null")
> ```

The `.where` clause doesn't look indented correctly.

---

*[src/test/scala/com/mozilla/telemetry/AddonsViewTest.scala, line 8 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KV_B7W73oN25VE0Vqhy:-KVeigoKVKLZgYfODIbF:bt748ga) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/159c767bac11d62ea7b11112b289b3f71bfb185b/src/test/scala/com/mozilla/telemetry/AddonsViewTest.scala#L8)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>
> As I see it, there are actually 3 different `Addon` classes in use:
> - The one used to parse the incoming JSON, which uses camelCase and all fields are optional
> - The one used to create literal structs for use in the Addon tests, which uses snake_case and no fields are optional (but they are nullable)
> - The one used in the cross-sectional dataset, which uses snake_case and all fields are optional.
> 
> I'm not sure how to combine these without adding even more code. Can we address this in a follow-up?
</details>
We can address this as a follow up if a bug has been filed for it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134)*

**Comment by mreid-moz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/test/scala/com/mozilla/telemetry/AddonsViewTest.scala, line 8 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KV_B7W73oN25VE0Vqhy:-KVewnZlUKlmYvbWShkH:bg64eoz) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/159c767bac11d62ea7b11112b289b3f71bfb185b/src/test/scala/com/mozilla/telemetry/AddonsViewTest.scala#L8)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> We can address this as a follow up if a bug has been filed for it.
</details>
Filed [Bug 1314997](https://bugzilla.mozilla.org/show_bug.cgi?id=1314997) to follow up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134)*

**Comment by mreid-moz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/test/scala/com/mozilla/telemetry/AddonsViewTest.scala, line 8 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KV_B7W73oN25VE0Vqhy:-KVewu-xtZb5_16J5jEo:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/159c767bac11d62ea7b11112b289b3f71bfb185b/src/test/scala/com/mozilla/telemetry/AddonsViewTest.scala#L8)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>
> Filed [Bug 1314997](https://bugzilla.mozilla.org/show_bug.cgi?id=1314997) to follow up.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134)*

**Comment by mreid-moz** [comment]
Review status: 4 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/scala/com/mozilla/telemetry/views/AddonsView.scala, line 94 at r5](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-KVeiXE8bMTwg0hKEW8n:-KVf4aPcHB9PXiaAccgR:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/9df6ececd520a790d6576c8b56b2f0e0713c0745/src/main/scala/com/mozilla/telemetry/views/AddonsView.scala#L94)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> The `.where` clause doesn't look indented correctly.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134)*

**Comment by vitillo** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r6.
Review status: 4 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/134#-:-KVf5WXK2X8Ar9lI0d9O:bnfp4nl)*

**Pull request merged**
