### PR TITLE
Add new cross sectional metrics

### PR DESCRIPTION
**Pull request by harterrt**
active_hours by day, geo country mode and number of configs,
architecture and locale mode.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/113)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by harterrt** [comment]
@vitillo PTAL. I'm particularly interested in your thoughts on whether architecture_Mode should be an Option[Option[A]] or Option[A].

**Comment by vitillo** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 31 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113#-KS70OlE6KnSROlS3HaF:-KS70OlE6KnSROlS3HaG:butu49g) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/a3e7f66c52c0622049c601fdd5689cb33171e11f/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L31)):*
> ```Scala
>   }
>   
>   def compare(that: Any, epsilon: Double = 1E-7) = {
> ```

We don't need this any longer as we moved to Scala 2.11 and so we can use case classes.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 62 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113#-KS712z3K5S2Q7gH-H8a:-KS712z3K5S2Q7gH-H8b:b-c3d2xb) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/a3e7f66c52c0622049c601fdd5689cb33171e11f/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L62)):*
> ```Scala
>   , val geo_country: Option[Seq[String]]
>   , val session_length: Option[Seq[Long]]
>   , val is_default_browser: Option[Seq[Option[Boolean]]]
> ```

This should be `Option[Seq[Boolean]]`. The same logic applies for the fields below (but using their respective types).

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 76 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113#-KS73DgRTXffsz-41_ds:-KS73DgVIkIT2c6AF8pY:b6mqqo4) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/a3e7f66c52c0622049c601fdd5689cb33171e11f/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L76)):*
> ```Scala
>   }
> 
>   def distinctConfigs[A](getter: (Longitudinal) => Seq[A]) = {
> ```

What about passing directly a `Seq[A]`? That said, I am not sure this operation needs its own separate helper method.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 85 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113#-KS72VA1MD4n9t_u3nNS:-KS72VA1MD4n9t_u3nNT:b-swtcrc) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/a3e7f66c52c0622049c601fdd5689cb33171e11f/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L85)):*
> ```Scala
>   }
> 
>   private def filterByDOW[A](getter: Longitudinal => Seq[A], dow: Int): Seq[A] = {
> ```

Not sure this is needs to be so generic if `filterByDOW` is invoked only with `session_length`.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 90 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113#-KS72ICEioxW08sx7sTK:-KS72ICEioxW08sx7sTL:bbs0cer) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/a3e7f66c52c0622049c601fdd5689cb33171e11f/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L90)):*
> ```Scala
> 
>   def activeHoursByDOW(dow: Int) = {
>     this.filterByDOW(_.session_length.getOrElse(Seq()), dow).sum/3600.0
> ```

Validation might be something we have to do here but it doesn't have to be addressed in this PR (e.g. dealing with huge negative session_lengths and what not).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113)*

**Comment by harterrt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 31 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113#-KS70OlE6KnSROlS3HaF:-KS7B-R6DeYpDUcltAV4:b-ck4ae2) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/a3e7f66c52c0622049c601fdd5689cb33171e11f/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L31)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> We don't need this any longer as we moved to Scala 2.11 and so we can use case classes.
</details>
We'll still need the compare method to handle comparison between floating point values, but I'll probably keep it in the testing suite. 

Have we finalized all of the changes to Airflow required to run Scala 2.11 jobs yet? I'd like to revert the case class workaround in a follow-up PR. 

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 62 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113#-KS712z3K5S2Q7gH-H8a:-KS7Bbx5ONQdJDbCJeOv:bc3n5ah) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/a3e7f66c52c0622049c601fdd5689cb33171e11f/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L62)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> This should be `Option[Seq[Boolean]]`. The same logic applies for the fields below (but using their respective types).
</details>
'is_default_browser' is and optional field of 'settings' [0] and settings is an optional field of the longitudinal table [1]. Empirically, we get parse errors if we force all members of the sequence to be present. 

[0] https://github.com/mozilla/telemetry-batch-view/blob/master/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L212
[1] https://github.com/mozilla/telemetry-batch-view/blob/master/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L449

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 76 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113#-KS73DgRTXffsz-41_ds:-KS7C_YTTHQq4oHL9702:bagsk2x) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/a3e7f66c52c0622049c601fdd5689cb33171e11f/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L76)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> What about passing directly a `Seq[A]`? That said, I am not sure this operation needs its own separate helper method.
</details>
Yeah, I agree. Removed.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 85 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113#-KS72VA1MD4n9t_u3nNS:-KS7Cm6XLdaMwH4JGFUS:bimyl8z) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/a3e7f66c52c0622049c601fdd5689cb33171e11f/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L85)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Not sure this is needs to be so generic if `filterByDOW` is invoked only with `session_length`.
</details>
Agreed. I thought I'd be adding two additional metrics based on this function (daysPossibleDow, daysActiveDow) but I have an alternative implementation now. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113)*

**Comment by vitillo** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 31 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113#-KS70OlE6KnSROlS3HaF:-KS7IKPbatmT1ZXp-ntC:b2lplse) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/a3e7f66c52c0622049c601fdd5689cb33171e11f/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L31)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary>
> We'll still need the compare method to handle comparison between floating point values, but I'll probably keep it in the testing suite. 
> 
> Have we finalized all of the changes to Airflow required to run Scala 2.11 jobs yet? I'd like to revert the case class workaround in a follow-up PR. 
</details>
We did finalize all the changes and deployed them to production. I am OK with a follow up patch; I will just ignore this code for now.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 62 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113#-KS712z3K5S2Q7gH-H8a:-KS7Io8sUnm7ILOi8XLq:b-kuzhaa) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/a3e7f66c52c0622049c601fdd5689cb33171e11f/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L62)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary>
> 'is_default_browser' is and optional field of 'settings' [0] and settings is an optional field of the longitudinal table [1]. Empirically, we get parse errors if we force all members of the sequence to be present. 
> 
> [0] https://github.com/mozilla/telemetry-batch-view/blob/master/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L212
> [1] https://github.com/mozilla/telemetry-batch-view/blob/master/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L449
</details>
Yep, that's correct.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 82 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113#-KS7JG9FEdsle569W5fr:-KS7JG9FEdsle569W5fs:bqs15lw) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/a20ef1b7a8a52d87759409044e657ac6e086f8c8/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L82)):*
> ```Scala
> 
>   private def filterByDOW(session_length: Seq[Long], dow: Int) = {
>     (session_length zip this.parsedSubmissionDate).filter(_._2.getDay == dow).map(_._1)
> ```

What about using `this.session_length`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113)*

**Comment by harterrt** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 31 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113#-KS70OlE6KnSROlS3HaF:-KS7LyoVEsAwK-Q3VNvp:bb73djm) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/a3e7f66c52c0622049c601fdd5689cb33171e11f/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L31)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> We did finalize all the changes and deployed them to production. I am OK with a follow up patch; I will just ignore this code for now.
</details>
SGTM

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 62 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113#-KS712z3K5S2Q7gH-H8a:-KS7M-vaDVbRI8i3-H6I:b3symxu) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/a3e7f66c52c0622049c601fdd5689cb33171e11f/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L62)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Yep, that's correct.
</details>
To be clear, I'll keep this as Option[Seq[Option[Boolean]]]

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 82 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113#-KS7JG9FEdsle569W5fr:-KS7MMD1xncnZGeQe0U_:b-gh1bgj) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/a20ef1b7a8a52d87759409044e657ac6e086f8c8/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L82)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> What about using `this.session_length`?
</details>
Simplified to one function for clarity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113)*

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113)*

**Comment by vitillo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113#-:-KS7MinEHMJCJepAhb-d:bnfp4nl)*

**Comment by vitillo** [comment]
Feel free to merge this once the test run to completion successfully.

**Comment by harterrt** [comment]
Tests are passing, merging now.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 90 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113#-KS72ICEioxW08sx7sTK:-KS7Rji1jFH5zVTqDcQ9:b2nhb2c) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/a3e7f66c52c0622049c601fdd5689cb33171e11f/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L90)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Validation might be something we have to do here but it doesn't have to be addressed in this PR (e.g. dealing with huge negative session_lengths and what not).
</details>
Ack

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/113#-:-KS7RmAFoX6c5MeEzLJh:b3sy3js)*

**Pull request merged**
