### PR TITLE
Bug 1306013 - Add startup crashes to crash_aggrregates stats

### PR DESCRIPTION
**Pull request by maurodoglio**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/166)

### CODE REVIEW

**Comment by harterrt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 143 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/166#-KaneE9wExU4mUXddJ_E:-KaneE9wExU4mUXddJ_F:btkuab8) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/04b142b840271ee3bf0e42a996b6e140f9b8bf90/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L143)):*
> ```Scala
>         "normalizedChannel" -> dimensions("channel").asInstanceOf[String],
>         "appName" -> dimensions("application").asInstanceOf[String],
> ```

Did you mean to add some tests here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/166)*

**Comment by maurodoglio** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 143 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/166#-KaneE9wExU4mUXddJ_E:-Kaqtyj-cYgNU-iDYCXJ:byl9s4) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/04b142b840271ee3bf0e42a996b6e140f9b8bf90/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L143)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary><blockquote>

Did you mean to add some tests here?
</blockquote></details>

Yes. That's what happens when you are sleep deprived :sleeping: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/166)*

**Comment by maurodoglio** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala, line 143 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/166#-KaneE9wExU4mUXddJ_E:-KbPFsFYE0PKLocKpSCu:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/cbdf156387f55c888ae3580b43a7add0119ba55c/src/test/scala/com/mozilla/telemetry/CrashAggregateViewTest.scala#L143)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary><blockquote>

Yes. That's what happens when you are sleep deprived :sleeping: 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/166)*

**Comment by maurodoglio** [comment]
@chutten could you please confirm that STARTUP_CRASH_DETECTED is the right place to look for startup_crashes?

**Comment by chutten** [comment]
I... don't know, actually. It seems reasonable, since it tracks to [nsAppStartup::TrackStartupCrashBegin](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/startup/nsAppStartup.cpp#889), but I think there ought to be an annotation on the crash pings themselves if it was caused by a startup crash.

Yeah, there's an annotation added by [nsAppRunner](https://dxr.mozilla.org/mozilla-central/rev/fbdfcecf0c774d2221f11aed5a504d5591c774e0/toolkit/xre/nsAppRunner.cpp#3232) which is whitelisted for inclusion in crash pings by [CrashManager](https://dxr.mozilla.org/mozilla-central/rev/fbdfcecf0c774d2221f11aed5a504d5591c774e0/toolkit/components/crashes/CrashManager.jsm#220).

**Comment by chutten** [comment]
Ack, clicking the "Update branch" button uses merge commits. Bleh. Sorry.

**Comment by maurodoglio** [comment]
Closing this for now as I'm not planning to work on it in the immediate future

**Pull request closed without merging**
