### PR TITLE
Add content histograms to longitudinal view

### PR DESCRIPTION
**Pull request by harterrt**
This change also makes it easy to add new histogram endpoints in the
future. Just add a path and suffix to histogramLocations or
keyedHistogramLocations. This whitelist updates both the parsing code
and the dataset schema.

I prototyped a version of this code which would remove the whitelist by
automatically scanning for new keys under "payload.processes". However,
we have to add these new keys/suffixes to the dataset schema.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/155)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by harterrt** [comment]
@vitillo, Please take a look

**Comment by harterrt** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala, line 22 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-K_8OqnqMF0wXOOXJH9O:-K_A48T3KzTlw8yHLHJE:bdeue0d) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0883cd09ccc696e6127b61bea4ecee22b6dfe8cc/src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala#L22)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary><blockquote>

I am not sure I understand why we would need to add (manually?) new keys/suffixes to the dataset schema if we want to automatically scan for new processes under `payload.processes`. 

Ideally we don't want to edit this job every time a new process type is added so it would be great if we can automate this part.
</blockquote></details>

Every histogram name needs to be registered in the schema generated by `buildSchema`[0]. Without this list of suffixes, we would need to scan through pings to collect new process types before generating the schema.

[0] https://github.com/mozilla/telemetry-batch-view/blob/master/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L187

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155)*

**Comment by vitillo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala, line 22 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-K_8OqnqMF0wXOOXJH9O:-K_A5enbCYyKwG3eA37h:b3qrehu) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0883cd09ccc696e6127b61bea4ecee22b6dfe8cc/src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala#L22)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary><blockquote>

Every histogram name needs to be registered in the schema generated by `buildSchema`[0]. Without this list of suffixes, we would need to scan through pings to collect new process types before generating the schema.

[0] https://github.com/mozilla/telemetry-batch-view/blob/master/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L187
</blockquote></details>

@dexterp37, is there a static list of valid processes somewhere? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155)*

**Comment by harterrt** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala, line 186 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-K_Bj8Da3N-otHdrmmPO:-K_Bj8DbIVGkBAcy2jC3:bwfdcw6) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0883cd09ccc696e6127b61bea4ecee22b6dfe8cc/src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala#L186)):*
> ```Scala
>         "payload.histograms" -> compact(render(histograms)),
>         "payload.keyedHistograms" -> compact(render(keyedHistograms)),
>         "payload.processes.content.histograms" -> compact(render(histograms)),
> ```

@vitillo, if I understand your comment in Bug 1325653 [0], this field will not be available in the Heka message, correct? I'll have to refactor this change to read directly from the payload object. Please confirm.

[0] https://bugzilla.mozilla.org/show_bug.cgi?id=1325653#c1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155)*

**Comment by vitillo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala, line 186 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-K_Bj8Da3N-otHdrmmPO:-K_DYBoQhmHcsxTN7BzO:bk65aw7) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0883cd09ccc696e6127b61bea4ecee22b6dfe8cc/src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala#L186)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary><blockquote>

@vitillo, if I understand your comment in Bug 1325653 [0], this field will not be available in the Heka message, correct? I'll have to refactor this change to read directly from the payload object. Please confirm.

[0] https://bugzilla.mozilla.org/show_bug.cgi?id=1325653#c1
</blockquote></details>

That was a more general comment about why things are what they are. 

I assumed you had already checked where exactly those fields sit in the payload; if not you can easily do that from the [Hindsight UI](https://hsadmin.trink.com/). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155)*

**Comment by Dexterp37** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala, line 22 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-K_8OqnqMF0wXOOXJH9O:-K_Dv3IHf8hNd9jXG2HV:b-lqfb1v) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0883cd09ccc696e6127b61bea4ecee22b6dfe8cc/src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala#L22)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary><blockquote>

@dexterp37, is there a static list of valid processes somewhere? 
</blockquote></details>

The list of Telemetry supported processes is only available [here](http://searchfox.org/mozilla-central/rev/51aa673e28802fe6ea89f4793721fc55334a6ac8/toolkit/components/telemetry/TelemetrySession.jsm#47): the ping section names are built from that by removing the "#" character. I might refactor this a bit as part of [bug 1278556](https://bugzilla.mozilla.org/show_bug.cgi?id=1278556) that is supposed to land soon-ish.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155)*

**Comment by vitillo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala, line 22 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-K_8OqnqMF0wXOOXJH9O:-K_V-J7NLZ8CcJ9IinHN:blv0vvt) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0883cd09ccc696e6127b61bea4ecee22b6dfe8cc/src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala#L22)):*
<details><summary><i>Previously, Dexterp37 (Alessio Placitelli) wrote…</i></summary><blockquote>

The list of Telemetry supported processes is only available [here](http://searchfox.org/mozilla-central/rev/51aa673e28802fe6ea89f4793721fc55334a6ac8/toolkit/components/telemetry/TelemetrySession.jsm#47): the ping section names are built from that by removing the "#" character. I might refactor this a bit as part of [bug 1278556](https://bugzilla.mozilla.org/show_bug.cgi?id=1278556) that is supposed to land soon-ish.
</blockquote></details>

Hm, that's not very parser friendly though. What about storing the valid process types in a yaml or json file somewhere?

---

*[src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala, line 186 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-K_Bj8Da3N-otHdrmmPO:-K_V-yQop8mVSH6h2jfn:b-c12d7z) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0883cd09ccc696e6127b61bea4ecee22b6dfe8cc/src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala#L186)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary><blockquote>

That was a more general comment about why things are what they are. 

I assumed you had already checked where exactly those fields sit in the payload; if not you can easily do that from the [Hindsight UI](https://hsadmin.trink.com/). 
</blockquote></details>

See also the corresponding [code](https://github.com/mozilla-services/data-pipeline/blob/master/heka/sandbox/decoders/extract_telemetry_dimensions.lua) that generates the data stored on S3.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155)*

**Comment by Dexterp37** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala, line 22 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-K_8OqnqMF0wXOOXJH9O:-K_YiDZ3xLBG8H6knyrA:b-u3ievn) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0883cd09ccc696e6127b61bea4ecee22b6dfe8cc/src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala#L22)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary><blockquote>

Hm, that's not very parser friendly though. What about storing the valid process types in a yaml or json file somewhere?
</blockquote></details>

I just filed [bug 1328230](https://bugzilla.mozilla.org/show_bug.cgi?id=1328230) for that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155)*

**Comment by harterrt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala, line 22 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-K_8OqnqMF0wXOOXJH9O:-K_jVYFnRDlGlol_KoWt:b-t3tf4y) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0883cd09ccc696e6127b61bea4ecee22b6dfe8cc/src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala#L22)):*
<details><summary><i>Previously, Dexterp37 (Alessio Placitelli) wrote…</i></summary><blockquote>

I just filed [bug 1328230](https://bugzilla.mozilla.org/show_bug.cgi?id=1328230) for that.
</blockquote></details>

@vitillo, can we continue with this PR and refactor once Bug 1328230 is complete?

---

*[src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala, line 32 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-K_8ON7-uz4KLfzYekkC:-K_flTGQK52ZM3OlXVfO:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0883cd09ccc696e6127b61bea4ecee22b6dfe8cc/src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala#L32)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary><blockquote>

s/HistFormat/HistogramFormat
</blockquote></details>

Done.

---

*[src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala, line 186 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-K_Bj8Da3N-otHdrmmPO:-K_jUFsWbc-mEcP39F3H:bjceco7) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0883cd09ccc696e6127b61bea4ecee22b6dfe8cc/src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala#L186)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary><blockquote>

See also the corresponding [code](https://github.com/mozilla-services/data-pipeline/blob/master/heka/sandbox/decoders/extract_telemetry_dimensions.lua) that generates the data stored on S3.
</blockquote></details>

Great. I refactored this change to read content histograms directly from the json payload. 

I ran the revised code over data from December 2016 and the results look good. The resulting data is in s3://telemetry-test-bucket/longitudinal/v20170103/.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155)*

**Comment by vitillo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala, line 22 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-K_8OqnqMF0wXOOXJH9O:-K_jWi4h_DPPoRrJRjuv:bo90zqn) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0883cd09ccc696e6127b61bea4ecee22b6dfe8cc/src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala#L22)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary><blockquote>

@vitillo, can we continue with this PR and refactor once Bug 1328230 is complete?
</blockquote></details>

@dexterp37, do you have a rough idea when that Bug will be tackled and how long it might take?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155)*

**Comment by vitillo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala, line 22 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-K_8OqnqMF0wXOOXJH9O:-K_jWsXqNvYe7ySEmoce:b-fg6g97) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0883cd09ccc696e6127b61bea4ecee22b6dfe8cc/src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala#L22)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary><blockquote>

@dexterp37, do you have a rough idea when that Bug will be tackled and how long it might take?
</blockquote></details>

@harterrt in the meantime you can assume that you are given a list with process names, e.g. List("content", "gpu"), instead of histogram locations. That will make it easier to adapt the code later on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155)*

**Comment by Dexterp37** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala, line 22 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-K_8OqnqMF0wXOOXJH9O:-K_n84lQGkqxiPK5O2aD:b-yu23l2) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0883cd09ccc696e6127b61bea4ecee22b6dfe8cc/src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala#L22)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary><blockquote>

@harterrt in the meantime you can assume that you are given a list with process names, e.g. List("content", "gpu"), instead of histogram locations. That will make it easier to adapt the code later on.
</blockquote></details>

We're going to tackle that as soon as bug 1278556 lands, so probably in a week or so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155)*

**Comment by harterrt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala, line 22 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-K_8OqnqMF0wXOOXJH9O:-Kaie2oMvZ9RZ4BHvKYn:b-wh8e34) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0883cd09ccc696e6127b61bea4ecee22b6dfe8cc/src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala#L22)):*
<details><summary><i>Previously, Dexterp37 (Alessio Placitelli) wrote…</i></summary><blockquote>

We're going to tackle that as soon as bug 1278556 lands, so probably in a week or so.
</blockquote></details>

@vitillo done. PTAL. 

I'm happy to refactor once bug 1328230 is closed, but I'd like to unblock this PR.

---

*[src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala, line 186 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-K_Bj8Da3N-otHdrmmPO:-Kai0rgxQh0tO9C5lvbR:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0883cd09ccc696e6127b61bea4ecee22b6dfe8cc/src/test/scala/com/mozilla/telemetry/LongitudinalTest.scala#L186)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary><blockquote>

Great. I refactored this change to read content histograms directly from the json payload. 

I ran the revised code over data from December 2016 and the results look good. The resulting data is in s3://telemetry-test-bucket/longitudinal/v20170103/.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155)*

**Comment by vitillo** [comment]
Reviewed 1 of 3 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala, line 22 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-K_8OqnqMF0wXOOXJH9O:-KaljBwFqToB6WCMxe6w:b-2bcn24) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0883cd09ccc696e6127b61bea4ecee22b6dfe8cc/src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala#L22)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary><blockquote>

@vitillo done. PTAL. 

I'm happy to refactor once bug 1328230 is closed, but I'd like to unblock this PR.
</blockquote></details>

OK, please open a Bug for the refactor.

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 805 at r4](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-Kalkir87QHcgPLJPWzi:-Kalkir87QHcgPLJPWzj:bu9oqm1) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/684d33ed5efd73ab98736cae925dbef56b3f4eba/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L805)):*
> ```Scala
>       // Get the payload of the Heka frame, which contains the payload for the
>       // main ping.
>       val payload = parse(x.getOrElse("payload", return).asInstanceOf[String]).extract[JValue]
> ```

Doesn't parse return a `JValue`? I am not sure why there is a call to `extract`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155)*

**Comment by harterrt** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala, line 22 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-K_8OqnqMF0wXOOXJH9O:-Kanr6EgTU2Cc1FaZkW2:bj6x9w7) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0883cd09ccc696e6127b61bea4ecee22b6dfe8cc/src/main/scala/com/mozilla/telemetry/histograms/Histogram.scala#L22)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary><blockquote>

OK, please open a Bug for the refactor.
</blockquote></details>

Done:
https://bugzilla.mozilla.org/show_bug.cgi?id=1332117

---

*[src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala, line 805 at r4](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-Kalkir87QHcgPLJPWzi:-KanoSA-1my2kGumlzSY:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/684d33ed5efd73ab98736cae925dbef56b3f4eba/src/main/scala/com/mozilla/telemetry/views/Longitudinal.scala#L805)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary><blockquote>

Doesn't parse return a `JValue`? I am not sure why there is a call to `extract`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155)*

**Comment by harterrt** [comment]
Rebased to clear the merge conflict.

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-:-KansezVDTGUmNo9ipG3:bd4ec36)*

**Comment by harterrt** [comment]
@vitillo RFAL

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-:-KarvgQjZw3berMuyPEv:bh8e8qb)*

**Comment by vitillo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/155#-:-Kas6G4wSB_dA1idU9a5:bnfp4nl)*

**Pull request merged**
