### PR TITLE
Bug 1314173 - Add gpu crashes to crash aggregate stats

### PR DESCRIPTION
**Pull request by maurodoglio**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/163)

### CODE REVIEW

**Comment by maurodoglio** [comment]
@harterrt could you please r?

**Comment by harterrt** [comment]
Can you update CrashAggregateView.md as well?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/163#-:-Ka3VPrP64E6bqxxBbD1:b-il0tes)*

**Comment by maurodoglio** [comment]
done

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/163#-:-Ka6mKHXBIt64jDjvgTW:bb7f2mf)*

**Comment by harterrt** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/163#-:-Ka7m0dnfjAqQ5pGhj4d:bnfp4nl)*

**Pull request merged**
