### PR TITLE
Bug 1316860 - Add CrashSummary batch view

### PR DESCRIPTION
**Pull request by maurodoglio**
The first version of CrashSummaryView is based on what's required by CrashAggregates. More fields can be easily added modifying the various case classes. ~It's still missing some tests for `CrashSummary.transformPayload`, but~ it's ready for a first look. I wrote a few tests to cover the few lines of logic in `transformPayload`, the compiler should cover the rest. 

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/161)

### CODE REVIEW

**Comment by harterrt** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala, line 56 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161#-Ka2svIKww6SylrFy9DX:-Ka2svILOPThtQSkwm84:b-k22wsz) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7671472077b91d93e407c2cfb2d982526546c8a9/src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala#L56)):*
> ```Scala
> 
> case class Meta(
>     Host: Option[String],
> ```

Please change to camelCase for consistency.

---

*[src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala, line 224 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161#-Ka2w3UOuKlJwitfvAAe:-Ka2w3UOuKlJwitfvAAf:b-nhlhep) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7671472077b91d93e407c2cfb2d982526546c8a9/src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala#L224)):*
> ```Scala
>         .where("sourceVersion") { case "4" => true }
>         .where("docType") { case "crash" => true }
>         .where("submissionDate") { case date if date == currentDate.toString("yyyyMMdd") => true }
> ```

Can we remove the conditional in this statement?

---

*[src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala, line 237 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161#-Ka2u2mNpnAp05g8Ymrk:-Ka2u2mOb0djQXNJ79xO:b3ghyu6) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7671472077b91d93e407c2cfb2d982526546c8a9/src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala#L237)):*
> ```Scala
>         }
>       })
>       val crashSummary = crashPings.flatMap(x => x).map(new CrashSummary(_))
> ```

Can `...flatMap(x=>x)...` be replaced with `flatten`?

---

*[src/test/scala/com/mozilla/telemetry/CrashSummaryViewTest.scala, line 13 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161#-Ka2tW7fddY-GHZ2G-yV:-Ka2tW7fddY-GHZ2G-yW:b-oozbon) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7671472077b91d93e407c2cfb2d982526546c8a9/src/test/scala/com/mozilla/telemetry/CrashSummaryViewTest.scala#L13)):*
> ```Scala
> 
>   def fixture = {
>     val crashPingsPath = getClass.getResource("/crash_ping_indented.json").getPath()
> ```

Out of curiosity, where's this ping from?

---

*[src/test/scala/com/mozilla/telemetry/CrashSummaryViewTest.scala, line 55 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161#-Ka2z43K_Niyzkcmh2NQ:-Ka2z43LvlestZUrIEen:bif11qm) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7671472077b91d93e407c2cfb2d982526546c8a9/src/test/scala/com/mozilla/telemetry/CrashSummaryViewTest.scala#L55)):*
> ```Scala
>       case _ => None
>     }
>     assert(crashSummary != None)
> ```

Do you mind verifying some of the fields in the `crashSummary` match your expectations? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161)*

**Comment by maurodoglio** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala, line 56 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161#-Ka2svIKww6SylrFy9DX:-Ka87TLRYpvbdDBF1bfr:b-sr8vv8) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7671472077b91d93e407c2cfb2d982526546c8a9/src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala#L56)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary><blockquote>

Please change to camelCase for consistency.
</blockquote></details>

These fields are named after the heka fields, if I change them they will not be parsed

---

*[src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala, line 237 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161#-Ka2u2mNpnAp05g8Ymrk:-Ka88WQ2Pw-YDIY5H12b:b-xwvl04) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7671472077b91d93e407c2cfb2d982526546c8a9/src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala#L237)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary><blockquote>

Can `...flatMap(x=>x)...` be replaced with `flatten`?
</blockquote></details>

flatten is not available on RDD, that's why I use flatMap

---

*[src/test/scala/com/mozilla/telemetry/CrashSummaryViewTest.scala, line 13 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161#-Ka2tW7fddY-GHZ2G-yV:-Ka89-KVfU4uLVvJW0-8:b-w1gf39) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7671472077b91d93e407c2cfb2d982526546c8a9/src/test/scala/com/mozilla/telemetry/CrashSummaryViewTest.scala#L13)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary><blockquote>

Out of curiosity, where's this ping from?
</blockquote></details>

I crafted it starting from a ping retrieved using moztelemetry. It's basically a humar readable version of a heka message.

---

*[src/test/scala/com/mozilla/telemetry/CrashSummaryViewTest.scala, line 55 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161#-Ka2z43K_Niyzkcmh2NQ:-Ka89aIY7O6fWV3eyI3j:b-urf366) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7671472077b91d93e407c2cfb2d982526546c8a9/src/test/scala/com/mozilla/telemetry/CrashSummaryViewTest.scala#L55)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary><blockquote>

Do you mind verifying some of the fields in the `crashSummary` match your expectations? 
</blockquote></details>

I'll verify the optional fields of CrashSummary, the rest should be covered by the compiler.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161)*

**Comment by maurodoglio** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala, line 224 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161#-Ka2w3UOuKlJwitfvAAe:-Ka8BFBDH1Rqag8T1Bbs:bk1qroe) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7671472077b91d93e407c2cfb2d982526546c8a9/src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala#L224)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary><blockquote>

Can we remove the conditional in this statement?
</blockquote></details>

That's needed to filter on submissionDate == today. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161)*

**Comment by harterrt** [comment]
Please squash these two commits into one.

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala, line 224 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161#-Ka2w3UOuKlJwitfvAAe:-KaCy0HQndAHgYl1if3a:br4v3hm) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7671472077b91d93e407c2cfb2d982526546c8a9/src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala#L224)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary><blockquote>

That's needed to filter on submissionDate == today. 
</blockquote></details>

Right, but can we simplify this to `case currentDate.toString(...) => true`?

---

*[src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala, line 237 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161#-Ka2u2mNpnAp05g8Ymrk:-KaD2KueBge469tLl6R3:b-nvr5v0) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7671472077b91d93e407c2cfb2d982526546c8a9/src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala#L237)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary><blockquote>

flatten is not available on RDD, that's why I use flatMap
</blockquote></details>

Ah, good to know!

---

*[src/test/scala/com/mozilla/telemetry/CrashSummaryViewTest.scala, line 55 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161#-Ka2z43K_Niyzkcmh2NQ:-KaD2VRf1R9FGgywdinz:b-ex1gk4) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7671472077b91d93e407c2cfb2d982526546c8a9/src/test/scala/com/mozilla/telemetry/CrashSummaryViewTest.scala#L55)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary><blockquote>

I'll verify the optional fields of CrashSummary, the rest should be covered by the compiler.
</blockquote></details>

I meant we should verify that the actual values look right, e.g.:
`assert(x.client_id == "my-client-id")`

It doesn't need to be comprehensive, but it would be good to verify.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161#-:-KaD3KtEKXKhHzOnREnX:b-a7fyal)*

**Comment by maurodoglio** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala, line 224 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161#-Ka2w3UOuKlJwitfvAAe:-KaD9JMTgKTFD-FnMJ2M:b88vr0t) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7671472077b91d93e407c2cfb2d982526546c8a9/src/main/scala/com/mozilla/telemetry/views/CrashSummaryView.scala#L224)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary><blockquote>

Right, but can we simplify this to `case currentDate.toString(...) => true`?
</blockquote></details>

hah now I see what you meant :smile_cat: . I don't think I can, the compiler complains if I use currentDate.toString(...) for some reason

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161)*

**Comment by maurodoglio** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/test/scala/com/mozilla/telemetry/CrashSummaryViewTest.scala, line 55 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161#-Ka2z43K_Niyzkcmh2NQ:-KaH1ImnzA8V9Vg5lfrW:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7671472077b91d93e407c2cfb2d982526546c8a9/src/test/scala/com/mozilla/telemetry/CrashSummaryViewTest.scala#L55)):*
<details><summary><i>Previously, harterrt (Ryan Harter) wrote…</i></summary><blockquote>

I meant we should verify that the actual values look right, e.g.:
`assert(x.client_id == "my-client-id")`

It doesn't need to be comprehensive, but it would be good to verify.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161)*

**Comment by harterrt** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/161#-:-KaHuSsbxtjQSXWjKRBZ:bnfp4nl)*

**Pull request merged**
