### PR TITLE
[Bug 1462795] auto deploy tag broken

### PR DESCRIPTION
**Pull request by haroldwoo**

### CODE REVIEW

**Comment by fbertsch** [comment]
@haroldwoo looks like this needs a rebase, why don't you wait to merge until https://github.com/mozilla/telemetry-batch-view/pull/427 is

**Comment by haroldwoo** [comment]
sure

**Comment by fbertsch** [comment]
@haroldwoo can you remove those extra releases?

**Comment by fbertsch** [comment]
@haroldwoo is this ready to merge?

**Pull request merged**
