### PR TITLE
Bug 1336488 - Add profile.creationDate to CrashSummaryView

### PR DESCRIPTION
**Pull request by chutten**
When during a profile's life do crashes happen? And what effect might they
have on the churn of users who might only just have started trying Firefox
for the first time?

Currently testing this on a day's data.

### CODE REVIEW

**Comment by chutten** [comment]
Seems to have worked. r?

s3://telemetry-test-bucket/chutten_profile_again/crash_summary/v1/submission_date=2017-01-10/

**Comment by chutten** [comment]
On second thought:
```
************************************
Total pings: 0
Processed pings: 0
Discarded pings: 2481986
************************************
```

Maybe I messed up someplace...

**Comment by maurodoglio** [comment]
Your patch is good, I think the problem has something to do with https://github.com/mozilla/telemetry-batch-view/pull/182#pullrequestreview-24045489. If you want to to run it on a date earlier than 2017-01-26, could you add a change to address that as well please?

**Comment by maurodoglio** [comment]
Actually, let me write a patch for it.

**Comment by maurodoglio** [comment]
I opened https://github.com/mozilla/telemetry-batch-view/pull/188 to fix the issue. Let's wait for that patch to be merged and we can then merge this one as well.

**Comment by maurodoglio** [comment]
Could you please rebase on top of latest master?

**Comment by chutten** [comment]
Getting there... Still digging myself out of post-PTO nonsense :S

**Pull request merged**
