### PR TITLE
Remove submission_date col from main_summary

### PR DESCRIPTION
**Pull request by fbertsch**
We should have added this to the bug squash :)

### CODE REVIEW

**Comment by SamPenrose** [comment]
Would it make sense to rename the existing column to "submission_date" to match analyst expectations?

**Comment by fbertsch** [comment]
@SamPenrose probably not, we have `submission_date_s3` uniform across most datasets now. If we want to change this one we would need to change them all, which means actually renaming every file in every dataset to have that partitioned name.

**Comment by mreid-moz** [comment]
I think this change requires some research and a communications plan - we want to minimize breakage and surprises. Research to figure out what (if anything) we know will be impacted, and comms to give folks a heads-up that this change is happening.

@fbertsch thoughts?

**Comment by fbertsch** [comment]
@mreid-moz definitely a good idea. I was also starting to question the efficiency difference in `submission_date` and `submission_date_s3`; parquet stores some stats about columns, presumably some `min` and `max` would be part of that. Given those, after reading the metadata for each parquet file in other `submission_date_s3` partitions, it wouldn't read the data itself (i.e. predicate pushdown).

**Comment by mreid-moz** [comment]
@fbertsch Let's test the efficiency! If there's minimal (or no) detectable difference, I don't think this is really worth the potential breakage.

**Comment by fbertsch** [comment]
Create bug 1387617 to investigate.

**Pull request closed without merging**
