### PR TITLE
Add content shutdown crashes as well

### PR DESCRIPTION
**Pull request by Uberi**
Based on https://github.com/mozilla/moz-crash-rate-aggregates/pulls/9 and https://github.com/mozilla/moz-crash-rate-aggregates/pulls/10

### CODE REVIEW

**Comment by vitillo** [comment]
https://github.com/mozilla/moz-crash-rate-aggregates/pulls/9 and https://github.com/mozilla/moz-crash-rate-aggregates/pulls/10 are not valid any longer so I am closing this.

**Comment by Uberi** [comment]
Since this is based on https://github.com/mozilla/moz-crash-rate-aggregates/pull/11, we probably still want this in order to make the Python and Scala version give the same results.

**Comment by vitillo** [comment]
We need this functionality in Scala as well, yes. But this PR is based on mozilla/moz-crash-rate-aggregates#9 and mozilla/moz-crash-rate-aggregates#10.

**Comment by vitillo** [comment]
See [Bug 1270547](https://bugzilla.mozilla.org/show_bug.cgi?id=1270547).

**Pull request closed without merging**
