### PR TITLE
Bug 1286262: Fix data types, add more fields.

### PR DESCRIPTION
**Pull request by mreid-moz**
Change the Windows service pack fields to Long type and add a few
other related fields.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/95)

### CODE REVIEW

**Comment by mreid-moz** [comment]
This has been tested on a subset of the data and the new / updated fields work as expected.

**Comment by vitillo** [comment]
Reviewed 3 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala, line 555 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/95#-KMdxWsUAyiEw8F4I2tp:-KMdxWsUAyiEw8F4I2tq:1686479519) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/99a2de2f05e9185e85e3c1424f320cccad2f2dab/src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala#L555)):*
> ```Scala
>           "os"                              -> "Darwin",
>           "os_version"                      -> "15.3.0",
>           "os_service_pack_major"           -> null,
> ```

Could we set real values here? The test-suite doesn't test the whole job but we can address this in a follow up PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/95)*

**Comment by mreid-moz** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala, line 555 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/95#-KMdxWsUAyiEw8F4I2tp:-KMe7TAC6rT03Wa59JPT:-580029260) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/99a2de2f05e9185e85e3c1424f320cccad2f2dab/src/test/scala/com/mozilla/telemetry/MainSummaryViewTest.scala#L555)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Could we set real values here? The test-suite doesn't test the whole job but we can address this in a follow up PR.
</details>
Ideally we'd add a second test ping from a windows machine - these fields don't make sense in a record from `Darwin`. We should really have a more comprehensive test dataset we can use from all the views. That's beyond the scope of this bug though...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/95)*

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/95)*

**Comment by vitillo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/95#-:-KMiIzKGvkpObDDs25Th:1417088721)*

**Pull request merged**
