### PR TITLE
Bug 1283471 - Update ClientCountView to use v3

### PR DESCRIPTION
**Pull request by mreid-moz**
MainSummaryView v3 uses a nested structure for one of the fields
used by the ClientCountView. Update the code and test case
accordingly.

Downstream consumers of ClientCountView should see no change.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/110)

### CODE REVIEW

**Comment by mreid-moz** [comment]
I've tested this (writing and reading back) using a few days' data, available at `s3://telemetry-test-bucket/client_count/v2016090820160910`

**Comment by vitillo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/ClientCountView.scala, line 74 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/110#-KRcqXcO6M1SoHyZPqzI:-KRcqXcO6M1SoHyZPqzJ:b9u3gkc) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/e05e13b4933276793bbd7d267986e6c36f1dd63a/src/main/scala/com/mozilla/telemetry/views/ClientCountView.scala#L74)):*
> ```Scala
>     sqlContext.udf.register("hll_create", hllCreate _)
> 
>     val df = sqlContext.read.load("s3://telemetry-parquet/main_summary/v3")
> ```

Since the schema of `client_count` didn't change we don't have to increase the version number.

---

*[src/test/scala/com/mozilla/telemetry/ClientCountViewTest.scala, line 47 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/110#-KRcrTXta8MsVu71o73d:-KRcrTXta8MsVu71o73e:bedc97k) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/e05e13b4933276793bbd7d267986e6c36f1dd63a/src/test/scala/com/mozilla/telemetry/ClientCountViewTest.scala#L47)):*
> ```Scala
>     "os_version" -> List("1.0", "1.1"),
>     "devtools_toolbox_opened_count" -> List(0, 42),
>     "loop_activity_counter.open_panel" -> List(0, 42))
> ```

Please use `List[Loop]`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/110)*

**Comment by mreid-moz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/ClientCountView.scala, line 74 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/110#-KRcqXcO6M1SoHyZPqzI:-KRcsLqntbut51J3qGE_:b-n4v4av) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/e05e13b4933276793bbd7d267986e6c36f1dd63a/src/main/scala/com/mozilla/telemetry/views/ClientCountView.scala#L74)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Since the schema of `client_count` didn't change we don't have to increase the version number.
</details>
This change is to read main_summary v3 instead of v2. The client_count version remains unchanged (it still reflects the date range each dataset covers).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/110)*

**Comment by vitillo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/views/ClientCountView.scala, line 74 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/110#-KRcqXcO6M1SoHyZPqzI:-KRctSnGPDUr0rDsJuuo:b-xx61yf) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/e05e13b4933276793bbd7d267986e6c36f1dd63a/src/main/scala/com/mozilla/telemetry/views/ClientCountView.scala#L74)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>
> This change is to read main_summary v3 instead of v2. The client_count version remains unchanged (it still reflects the date range each dataset covers).
</details>
Whoops

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/110)*

**Comment by mreid-moz** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/scala/com/mozilla/telemetry/ClientCountViewTest.scala, line 47 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/110#-KRcrTXta8MsVu71o73d:-KRcvs1Sfg4ZviuxOj4W:b3oxg9z) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/e05e13b4933276793bbd7d267986e6c36f1dd63a/src/test/scala/com/mozilla/telemetry/ClientCountViewTest.scala#L47)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Please use `List[Loop]`.
</details>
Good call. That makes it cleaner.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/110)*

**Comment by vitillo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/110#-:-KRd51mOb_A3ikrKr3Jg:bnfp4nl)*

**Pull request merged**
