### PR TITLE
Train with addon ids

### PR DESCRIPTION
**Pull request by Dexterp37**
This changes the addon recommender to fetch the addon database from addons.mozilla.org. We use the dumped information to prune commercial, unreviewed, privated or, in general, unlisted addons before training the model.

We also use the dumped information to get the addon name from the reported default locale, instead of relying on data coming from the clients.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/97)

### CODE REVIEW

**Comment by vitillo** [comment]
Please change the subject of the commit messages to use the [imperative mood](http://chris.beams.io/posts/git-commit/). 

Please specify the [why](http://chris.beams.io/posts/git-commit/) of the change in the body of the commit message and not in the subject.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[build.sbt, line 28 \[r3\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNWyLrXaFp6lhc6Ro_R:-KNWyLrXaFp6lhc6Ro_S:-737715812) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/75ccb64f9a3b063154ea3d4d0c14e9185a7f515b/build.sbt#L28)):*
> ```Scala
>     libraryDependencies += "org.apache.spark" %% "spark-sql" % "1.6.1",
>     libraryDependencies += "org.apache.spark" %% "spark-mllib" % "1.6.1",
>     libraryDependencies += "org.apache.spark" %% "spark-hive" % "1.6.1",
> ```

This change should be part of the previous commit.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 42 \[r4\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNWycDO-Mzy_gnCtpFO:-KNWycDPXC7nbRl2aKIV:-6749106) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ffa7437c422f82a7e211eb424fd8116b791769c/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L42)):*
> ```Scala
> private case class ItemFactors(id: Int, features: Array[Float])
> 
> private case class AMOAddonInfo(guid: String, default_locale: String, name: Map[String,String])
> ```

Let's move the AMO stuff in its own file.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 92 \[r4\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNWzCKDJXUkfVqoYzEl:-KNWzCKDJXUkfVqoYzEm:-1782744813) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ffa7437c422f82a7e211eb424fd8116b791769c/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L92)):*
> ```Scala
>   }
> 
>   private def fetchAddonsDatabase(): Map[String, AMOAddonInfo] = {
> ```

Let's encapsulate this functionality in a class that represents the AMO database.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 94 \[r4\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNX1Dsqc7koDkaZbAvP:-KNX1Dsqc7koDkaZbAvQ:-433946757) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ffa7437c422f82a7e211eb424fd8116b791769c/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L94)):*
> ```Scala
>   private def fetchAddonsDatabase(): Map[String, AMOAddonInfo] = {
>     // This API URI will fetch all the public addons for Firefox, sorting them by creation date.
>     var amoRequestURI = "https://addons.mozilla.org/api/v3/addons/search/?app=firefox&sort=created&type=extension"
> ```

Please don't use `vars` unless necessary.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 102 \[r4\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNX1Xd-F_8QK8lqALUn:-KNX1Xd-F_8QK8lqALUo:1775988922) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ffa7437c422f82a7e211eb424fd8116b791769c/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L102)):*
> ```Scala
>     // We query the addon /search API endpoint to get all the addons with fewer requests. Each result "page"
>     // contains a link to the next batch of results.
>     do {
> ```

Would be nice to have this implemented recursively so we can get rid of the `var`.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 127 \[r4\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNWz4vkcAKZR84vsXoC:-KNWz4vlmcoCjc-fQYwr:-1782744813) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ffa7437c422f82a7e211eb424fd8116b791769c/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L127)):*
> ```Scala
>   }
> 
>   private def getAddonsDatabase(outputDir: String): Map[String, AMOAddonInfo] = {
> ```

Let's encapsulate this functionality in a class that represents the AMO database.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 131 \[r4\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNWyoGDHbhCB-4faRiA:-KNWyoGEaTm0Py2ko9hO:-1339202200) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ffa7437c422f82a7e211eb424fd8116b791769c/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L131)):*
> ```Scala
>     val dbPath = Paths.get(s"$outputDir/addons_database.json")
>     if (Files.exists(dbPath)) {
>       println(s"Hitting addon database cache at $dbPath")
> ```

Please use logging instead of prints.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 133 \[r4\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNWyxE8VyaBRWXp7TFS:-KNWyxE9YkMHVnI8AuxC:-1019697754) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ffa7437c422f82a7e211eb424fd8116b791769c/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L133)):*
> ```Scala
>       println(s"Hitting addon database cache at $dbPath")
>       val cachedMap = parse(Source.fromFile(dbPath.toString()).mkString).extract[Map[String, AMOAddonInfo]]
>       return cachedMap
> ```

Please avoid using return.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 138 \[r4\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNWz_1WI7ZQ_BUGGimG:-KNWz_1ZsjlhEMBKC1bc:2032904436) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ffa7437c422f82a7e211eb424fd8116b791769c/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L138)):*
> ```Scala
>     // Otherwise fetch it from addons.mozilla.org (might take some time..) and cache it.
>     val fetchedAddonsMap = fetchAddonsDatabase()
>     val serializedItemFactors = write(fetchedAddonsMap)
> ```

Why is this variable called `serializedItemFactors`?

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 193 \[r4\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNX-JTPRx2SNuixkH_2:-KNX-JTQkRvhj3N3XrSf:1517766587) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ffa7437c422f82a7e211eb424fd8116b791769c/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L193)):*
> ```Scala
>           (addonId, meta) <- addons
>           if !List("loop@mozilla.org","firefox@getpocket.com", "e10srollout@mozilla.org", "firefox-hotfix@mozilla.org").contains(addonId) &&
>              addonsDatabase.exists(_._1 == addonId)
> ```

Use the `contains` method.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 242 \[r4\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNX-mKhQVZ0AESqB1WD:-KNX-mKiqsxhBs1eYVM6:1567615609) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ffa7437c422f82a7e211eb424fd8116b791769c/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L242)):*
> ```Scala
>     // Serialize add-on mapping
>     val addonMapping = clientAddons
>       .map{ case (_, addonId, _, hashedAddonId) => (hashedAddonId, addonsDatabase.get(addonId) match {
> ```

Please move this functionality to a method of the class that is going to represent the AMO database.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 243 \[r4\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNX0hKbXoM7vsDstzvd:-KNX0hKbXoM7vsDstzve:-1280933704) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ffa7437c422f82a7e211eb424fd8116b791769c/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L243)):*
> ```Scala
>     val addonMapping = clientAddons
>       .map{ case (_, addonId, _, hashedAddonId) => (hashedAddonId, addonsDatabase.get(addonId) match {
>         case Some(addonInfo) => addonInfo.name.getOrElse(addonInfo.default_locale, s"Name for default locale not found $addonInfo.default_locale")
> ```

Let's log in case of failure and ignore the add-on altogether.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 243 \[r4\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNX15sR7y950YDGi8F8:-KNX15sSA5rhgrIYxmXX:711491341) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ffa7437c422f82a7e211eb424fd8116b791769c/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L243)):*
> ```Scala
>     val addonMapping = clientAddons
>       .map{ case (_, addonId, _, hashedAddonId) => (hashedAddonId, addonsDatabase.get(addonId) match {
>         case Some(addonInfo) => addonInfo.name.getOrElse(addonInfo.default_locale, s"Name for default locale not found $addonInfo.default_locale")
> ```

How is `default_locale` defined?

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 244 \[r4\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNX09PC2aBFPXC_VQ4u:-KNX09PC2aBFPXC_VQ4v:-1280933704) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ffa7437c422f82a7e211eb424fd8116b791769c/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L244)):*
> ```Scala
>       .map{ case (_, addonId, _, hashedAddonId) => (hashedAddonId, addonsDatabase.get(addonId) match {
>         case Some(addonInfo) => addonInfo.name.getOrElse(addonInfo.default_locale, s"Name for default locale not found $addonInfo.default_locale")
>         case None => s"GUID not in DB: $addonId"
> ```

Let's log in case of failure and ignore the add-on altogether.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 262 \[r5\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNX28ijDq0sQQiThJmD:-KNX28ik_sb5SWyblp92:-1837511929) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0eae45ce2bb324fe9b5e777bedc63559b6c49f3c/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L262)):*
> ```Scala
>     // Serialize model to HDFS and then copy it to the local machine.
>     try {
>       model.write.overwrite().save(s"$outputDir/als.model")
> ```

Could you please verify that Spark doesn't have a better way of doing this natively and if not add a comment?

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 264 \[r5\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNX1yexzar25Q2Y6-rA:-KNX1yezmRiRFVRb0wut:-1570468132) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0eae45ce2bb324fe9b5e777bedc63559b6c49f3c/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L264)):*
> ```Scala
>       model.write.overwrite().save(s"$outputDir/als.model")
>       val copyCmdOutput = s"hdfs dfs -get $outputDir/als.model $outputDir/".!!
>       println("Command output " + copyCmdOutput)
> ```

Use logging instead of prints.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 266 \[r5\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNX2LkD-fASiG3oE5h4:-KNX2LkE-SQkeQx6SbGX:1841112878) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0eae45ce2bb324fe9b5e777bedc63559b6c49f3c/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L266)):*
> ```Scala
>       println("Command output " + copyCmdOutput)
>     } catch {
>       case e: Exception => println("H: " + e.getMessage)
> ```

Please use logging. When do you expect this to fail?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-:-KNWw5K5HEAZLRbAfxV7:-1484589501)*

**Comment by Dexterp37** [comment]
@vitillo , should we use logging for printing the model statistics as well?

**Comment by vitillo** [comment]
Yeah, that makes sense.

**Comment by Dexterp37** [comment]
Cool, now that's ready for a second pass. r? @vitillo

**Comment by vitillo** [comment]
You should comment on the unresolved issues in `reviewable` once you addressed them so that I can mark them as closed. 

---

Reviewed 2 of 2 files at r6, 2 of 2 files at r7, 2 of 2 files at r8, 1 of 1 files at r9.
Review status: 1 of 3 files reviewed at latest revision, 19 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNleXuQ4kJwQ2EOmtmF:-KNleXuQ4kJwQ2EOmtmG:617297958) (no related file):*
Please merge commit 8fc41ff in commit fe9cb50.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 264 \[r9\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNlexolr_8WhsaLXq5k:-KNlexommoFPfI4_PfmM:1579920985) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/afcb8e50dee1acd5573d3c518cc8eb61c12b1c77/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L264)):*
> ```Scala
>       model.write.overwrite().save(s"$outputDir/als.model")
>       val copyCmdOutput = s"hdfs dfs -get $outputDir/als.model $outputDir/".!!
>       println("Command output " + copyCmdOutput)
> ```

Please use logging.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-:-KNldDxxjJgfvgRBGk6i:-1646024078)*

**Comment by vitillo** [comment]
Reviewed 2 of 2 files at r10.
Review status: all files reviewed at latest revision, 27 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala, line 20 \[r10\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNlihl5yI149qIcTta4:-KNlihl6rlZhtMAqgMrm:-2002173799) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8fc41ff7c6488d92f070ac00e793c9b51c9addaa/src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala#L20)):*
> ```Scala
> 
> /**
>   * This object is responsible for building a local cache of the addons on addons.mozilla.org (AMO),
> ```

Please move the comma one line up.

---

*[src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala, line 20 \[r10\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNljxvMjtxMWsiGuCbI:-KNljxvNbNC6s759rY9d:948030774) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8fc41ff7c6488d92f070ac00e793c9b51c9addaa/src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala#L20)):*
> ```Scala
> 
> /**
>   * This object is responsible for building a local cache of the addons on addons.mozilla.org (AMO),
> ```

Change to: The `AMODatabase` singleton encapsulates a local version of the addons.mozilla.org (AMO) database

---

*[src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala, line 24 \[r10\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNlipMy4nt-FDqTLmRn:-KNlipMy4nt-FDqTLmRo:-196232452) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8fc41ff7c6488d92f070ac00e793c9b51c9addaa/src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala#L24)):*
> ```Scala
>   *
>   * There are non-publicly available addons on AMO. This could happen bacause, the add-on:
>   *
> ```

Please remove empty line.

---

*[src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala, line 72 \[r10\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNlg2lpWH-1jRcFmKST:-KNlg2lqUIeAaPz7IJYQ:883354525) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8fc41ff7c6488d92f070ac00e793c9b51c9addaa/src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala#L72)):*
> ```Scala
> 
>   /**
>     * Fetch a copy of the AMO addons database or returns a cached local copy if
> ```

s/returns/return

---

*[src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala, line 74 \[r10\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNlg9zB-BdAlG3j5rlm:-KNlg9zB-BdAlG3j5rln:-1640616817) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8fc41ff7c6488d92f070ac00e793c9b51c9addaa/src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala#L74)):*
> ```Scala
>     * Fetch a copy of the AMO addons database or returns a cached local copy if
>     * available.
>     * @param outputDir The directory where the local cached copy should be saved.
> ```

s/outputDir/cacheDirectory

---

*[src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala, line 76 \[r10\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNlfhXrpQgfzAPga1Bz:-KNlfhXrpQgfzAPga1C-:-345629164) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8fc41ff7c6488d92f070ac00e793c9b51c9addaa/src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala#L76)):*
> ```Scala
>     * @param outputDir The directory where the local cached copy should be saved.
>     * @return A map of addon GUIDs to their info.
>     */
> ```

This looks a bit weird. Please the constructor to fetch a copy of the AMO database. It probably makes sense to set a default argument for `outputDir` or remove the parameter entirely. Furthermore, how do you plan to handle cache invalidation? You might want to add a comment that explains that the "read-from-disk" functionality is needed only for testing purposes and so cache invalidation isn't really an issue.

---

*[src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala, line 80 \[r10\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNlhRpUtrtNQmnf1R2s:-KNlhRpUtrtNQmnf1R2t:1401946977) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8fc41ff7c6488d92f070ac00e793c9b51c9addaa/src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala#L80)):*
> ```Scala
>     // If we have a cached copy of the request handy, use that.
>     val dbPath = Paths.get(s"$outputDir/addons_database.json")
>     if (Files.exists(dbPath)) {
> ```

If two or more `get`s are invoked concurrently this method will likely run in a raise condition; one more reason to do this during construction time.

---

*[src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala, line 99 \[r10\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNljHyYCfGJOB65Yl6h:-KNljHyYCfGJOB65Yl6i:1315044633) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8fc41ff7c6488d92f070ac00e793c9b51c9addaa/src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala#L99)):*
> ```Scala
>     *         unless the database is corrupted.
>     */
>   def getAddonNameById(addonDb: Map[String, AMOAddonInfo], addonId: String): Option[String] = {
> ```

There is no need to pass `addonDb` as it should be a private property of the singleton. Furthermore, `addonDb` should be named `addonDB`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97)*

**Comment by vitillo** [comment]
Review status: all files reviewed at latest revision, 27 unresolved discussions.

---

*[src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala, line 80 \[r10\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNlhRpUtrtNQmnf1R2s:-KNlkp65l3iGWg0C8Rz2:-1160317208) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8fc41ff7c6488d92f070ac00e793c9b51c9addaa/src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala#L80)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> If two or more `get`s are invoked concurrently this method will likely run in a raise condition; one more reason to do this during construction time.
</details>
Even if we move this in the constructor, the raise condition might still happen though if multiple JVMs are running. Can we make this functionality atomic?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97)*

**Comment by Dexterp37** [comment]
Ah, sorry for the mess. That's the first time I'm using this tool, I was assuming all things were resolved unless "commented".

---

Review status: 1 of 3 files reviewed at latest revision, 28 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNleXuQ4kJwQ2EOmtmF:-KOiW3pPFbdijE2jpp8B:b-896fix) (no related file):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Please merge commit 8fc41ff in commit fe9cb50.
</details>
Done.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 243 \[r4\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNX15sR7y950YDGi8F8:-KOiWATIJm2CvJ5Yy_zz:b-49m5t7) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/7ffa7437c422f82a7e211eb424fd8116b791769c/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L243)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> How is `default_locale` defined?
</details>
It's a string containing the name of the default locale for the addon, e.g. "it_IT", as there can be addons with no English language. So we pick the name/info for the default locale, as they must be available.

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 262 \[r5\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNX28ijDq0sQQiThJmD:-KOiWjLtM_qH-BBKjkFn:b-fc2be4) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0eae45ce2bb324fe9b5e777bedc63559b6c49f3c/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L262)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Could you please verify that Spark doesn't have a better way of doing this natively and if not add a comment?
</details>
I tried to use the HDFS API there, but I trip on the same permission issues that we encountered using `model.write.overwrite().save(s"file://$outputDir/als.model")`

---

*[src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala, line 266 \[r5\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNX2LkD-fASiG3oE5h4:-KOiXIa8hMJz5F_tFmmL:b48leqf) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/0eae45ce2bb324fe9b5e777bedc63559b6c49f3c/src/main/scala/com/mozilla/telemetry/ml/AddonRecommender.scala#L266)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Please use logging. When do you expect this to fail?
</details>
This is expected to fail if there was some issue writing the the model to file or copying the model from HDFS to the local machine. I've added a comment there.

---

*[src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala, line 76 \[r10\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNlfhXrpQgfzAPga1Bz:-KOimIO0I0TG2aFJTLMP:b-l8d7c1) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/8fc41ff7c6488d92f070ac00e793c9b51c9addaa/src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala#L76)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> This looks a bit weird. Please the constructor to fetch a copy of the AMO database. It probably makes sense to set a default argument for `outputDir` or remove the parameter entirely. Furthermore, how do you plan to handle cache invalidation? You might want to add a comment that explains that the "read-from-disk" functionality is needed only for testing purposes and so cache invalidation isn't really an issue.
</details>
Good points. I've removed the parameter and added a comment about the invalidation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-:-KOiUQwsWnUMGJ96CSkM:b-vhnktp)*

**Comment by vitillo** [comment]
Reviewed 2 of 2 files at r11, 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KNleXuQ4kJwQ2EOmtmF:-KOoDBCte2Y7xO64rvtn:b-17b176) (no related file):*
<details><summary><i>Previously, Dexterp37 (Alessio Placitelli) wrote…</i></summary>
> Done.
</details>
Next time please mark open issues as solved in reviewable when you have addressed them.

---

*[src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala, line 17 \[r11\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KOju18ezKMlpyHJw-7w:-KOju18ezKMlpyHJw-7x:b11w0kr) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/1ceab37764aaeb9a9d443e11edacad57cad53bb8/src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala#L17)):*
> ```Scala
> 
> private case class AMOAddonPage(previous: String, next: String, results: List[AMOAddonInfo])
> case class AMOAddonInfo(guid: String, default_locale: String, name: Map[String,String])
> ```

Can this class be made private?

---

*[src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala, line 105 \[r11\]](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-KOoDlaTwcHWi_fM4eDk:-KOoDlaTwcHWi_fM4eDl:bd5hb7s) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/1ceab37764aaeb9a9d443e11edacad57cad53bb8/src/main/scala/com/mozilla/telemetry/ml/AMODatabase.scala#L105)):*
> ```Scala
>     addonDB.get(addonId) match {
>       case Some(addonInfo) => addonInfo.name.get(addonInfo.default_locale)
>       case None => {
> ```

There is no need for curly braces here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97)*

**Comment by vitillo** [comment]
Reviewed 2 of 2 files at r13.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97)*

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r14.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97)*

**Comment by vitillo** [comment]
:lgtm: Great job Alessio!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/97#-:-KOx4qgPPce1lWMB5efq:bm2mk6e)*

**Pull request merged**
