### PR TITLE
Cross Sectional style cleanup

### PR DESCRIPTION
**Pull request by harterrt**
@vitillo, let me know if you'd like to review these commits in separate PRs.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/144)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 16 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/144#-KWhs70445rCAj6CloFB:-KWhs705mOPec0OEAVK3:bb7m8d7) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/e4a01b7da1386c5bee07e0fe26a3eb121488d61c/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L16)):*
> ```Scala
>   // Option[Seq[A]] in this dataset, and calling _.map(_.map(...)) obfuscates
>   // the code. This alias allows us to instead write: _.ifExists(_.map(...))
>   def ifExists[B](f: (A) => B) = from.map(f) 
> ```

What about calling it `ifDefined` since `Option` has a method called `isDefined`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/144)*

**Comment by harterrt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala, line 16 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/144#-KWhs70445rCAj6CloFB:-KWikIb1LcA2fNe1A0gk:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/e4a01b7da1386c5bee07e0fe26a3eb121488d61c/src/main/scala/com/mozilla/telemetry/views/CrossSectionalView.scala#L16)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> What about calling it `ifDefined` since `Option` has a method called `isDefined`?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/144)*

**Comment by vitillo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/144#-:-KWrWpxxpdq8KRx7yCoY:bnfp4nl)*

**Comment by vitillo** [comment]
Please rebase this patch.

**Comment by harterrt** [comment]
Done

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/144#-:-KX1VNfXvK-mR4E-Xkhu:bb6un1j)*

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r4.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/144)*

**Pull request merged**
