### PR TITLE
Move package to Spark 2.0

### PR DESCRIPTION
**Pull request by vitillo**
I plan to enlist help moving our jobs to Spark 2.0. I don't expect big issues but I think it makes sense that each owner schedules his jobs with Spark 2.0 through Airflow and makes sure that it works as expected. 

I will file some bugs in the next days and provide one or more examples of how to schedule a Scala job from Airflow with Spark 2.0.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-batch-view/111)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by Dexterp37** [comment]
The AddonRecommender raises some deprecation warnings due to the uses of hiveContext, but still works thanks to your changes. So I guess any additional changes to that code can come as part of the bugs you wanted to spawn.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala, line 7 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/111#-KRgwKf4MKZ5slx3Cs61:-KRgwKf5bAxDZz9-mvHo:b-dy275g) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/82cccfe64e65c7c336fd31dbf76452d925e83c59/src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala#L7)):*
> ```Scala
> import org.apache.spark.sql.{Row, SQLContext, SaveMode}
> import org.apache.spark.{SparkConf, SparkContext}
> import org.apache.spark.util.LongAccumulator
> ```

I'm not familiar with this Scala module, but I see that the old Accumulator was marked as deprecated in 2.0 and a new one was introduced. Hence, LGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/111#-:-KRgwgu8yKemuad2VLjj:bffiicj)*

**Comment by Dexterp37** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/111#-:-KRgx5agzcLj4kYCKtKF:bnfp4nl)*

**Comment by mreid-moz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala, line 12 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/111#-KRha_MPP_Ix4wOG157a:-KRha_MQzcMVUyNuRliV:burpwae) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/82cccfe64e65c7c336fd31dbf76452d925e83c59/src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala#L12)):*
> ```Scala
> import org.json4s.jackson.JsonMethods._
> import org.rogach.scallop._
> import com.mozilla.telemetry.heka.{Dataset}
> ```

Don't need braces around a single import

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/111)*

**Comment by vitillo** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala, line 12 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/111#-KRha_MPP_Ix4wOG157a:-KRhohDN_Z2UVI0yqT5m:b-896fix) ([raw file](https://github.com/mozilla/telemetry-batch-view/blob/82cccfe64e65c7c336fd31dbf76452d925e83c59/src/main/scala/com/mozilla/telemetry/views/CrashAggregateView.scala#L12)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>
> Don't need braces around a single import
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/111)*

**Comment by mreid-moz** [comment]
:lgtm:

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-batch-view/111#-:-KRhvbqiCi9pCkZn-SxV:bnfp4nl)*

**Pull request merged**
